/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Schema for the shape service to contain the BioZernike descriptors data that describe PDB volumes at different granularities.
 */
export interface ShapeDescriptor {
    rcsb_shape_container_identifiers: {
        /**
         * Assembly identifier.
         */
        assembly_id?: string;
        /**
         * Entry identifier.
         */
        entry_id: string;
        /**
         * Polymer entity instance identifier.
         */
        asym_id?: string;
    };
    /**
     * The maximum order of Zernike moments (the n index in Ω_nlm) that are stored in the zernike_invariants object.
     */
    max_order_zernike_invariants: number;
    /**
     * The maximum order of Zernike moments (the n index in Ω_nlm) that are stored in the zernike_align object.
     */
    max_order_zernike_align: number;
    /**
     * @minItems 1
     */
    zernike_invariants: [
        {
            /**
             * 0 is for the special case of the classic Zernike/Novotni invariants (norms of Ω_nlm, a.k.a. 3DZD, a.k.a. fingerprints), any other positive integer represents the order of the Canterakis norm as described in Guzenko et al 2019.
             */
            norm_order: number;
            /**
             * @minItems 1
             */
            values: [number, ...number[]];
            [k: string]: unknown;
        },
        ...{
            /**
             * 0 is for the special case of the classic Zernike/Novotni invariants (norms of Ω_nlm, a.k.a. 3DZD, a.k.a. fingerprints), any other positive integer represents the order of the Canterakis norm as described in Guzenko et al 2019.
             */
            norm_order: number;
            /**
             * @minItems 1
             */
            values: [number, ...number[]];
            [k: string]: unknown;
        }[]
    ];
    /**
     * @minItems 1
     */
    geom_invariants: [number, ...number[]];
    /**
     * @minItems 1
     */
    zernike_align: [number, ...number[]];
    /**
     * @minItems 3
     */
    volume_center: [number, number, number, ...number[]];
    /**
     * Type of the object represented by the descriptor, used for independent searches.
     */
    shape_entity_type: "assembly" | "chain" | "domain";
    rcsb_latest_revision: {
        /**
         * The major version number of the latest revision.
         */
        major_revision?: number;
        /**
         * The minor version number of the latest revision.
         */
        minor_revision?: number;
        /**
         * The release date of the latest revision item.
         */
        revision_date?: string;
        [k: string]: unknown;
    };
}
