/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON schema for nonpolymer entity core.
 */
export interface CoreNonpolymerEntity {
  pdbx_entity_nonpoly?: {
    /**
     * This data item is a pointer to _chem_comp.id in the CHEM_COMP category.
     */
    comp_id?: string;
    /**
     * This data item is a pointer to _entity.id in the ENTITY category.
     */
    entity_id: string;
    /**
     * A name for the non-polymer entity
     */
    name?: string;
    /**
     * For non-polymer BIRD molecules the BIRD identifier for the entity.
     */
    rcsb_prd_id?: string;
  };
  rcsb_nonpolymer_entity?: {
    /**
     * A description of special aspects of the entity.
     */
    details?: string;
    /**
     * Formula mass (KDa) of the entity.
     */
    formula_weight?: number;
    /**
     * A description of the nonpolymer entity.
     */
    pdbx_description?: string;
    /**
     * The number of molecules of the nonpolymer entity in the entry.
     */
    pdbx_number_of_molecules?: number;
  };
  /**
   * @minItems 1
   */
  rcsb_nonpolymer_entity_annotation?: [
    {
      /**
       * An identifier for the annotation.
       */
      annotation_id?: string;
      /**
       * Identifies the version of the annotation assignment.
       */
      assignment_version?: string;
      /**
       * Non-polymer(ligand) chemical component identifier for the entity.
       */
      comp_id?: string;
      /**
       * A description for the annotation.
       */
      description?: string;
      /**
       * A name for the annotation.
       */
      name?: string;
      /**
       * Code identifying the individual, organization or program that
       *  assigned the annotation.
       */
      provenance_source?: string;
      /**
       * A type or category of the annotation.
       */
      type?: "SUBJECT_OF_INVESTIGATION";
      annotation_lineage?: {
        /**
         * Members of the annotation lineage as parent lineage depth (1-N)
         */
        depth?: number;
        /**
         * Members of the annotation lineage as parent class identifiers.
         */
        id?: string;
        /**
         * Members of the annotation lineage as parent class names.
         */
        name?: string;
      }[];
    },
    ...{
      /**
       * An identifier for the annotation.
       */
      annotation_id?: string;
      /**
       * Identifies the version of the annotation assignment.
       */
      assignment_version?: string;
      /**
       * Non-polymer(ligand) chemical component identifier for the entity.
       */
      comp_id?: string;
      /**
       * A description for the annotation.
       */
      description?: string;
      /**
       * A name for the annotation.
       */
      name?: string;
      /**
       * Code identifying the individual, organization or program that
       *  assigned the annotation.
       */
      provenance_source?: string;
      /**
       * A type or category of the annotation.
       */
      type?: "SUBJECT_OF_INVESTIGATION";
      annotation_lineage?: {
        /**
         * Members of the annotation lineage as parent lineage depth (1-N)
         */
        depth?: number;
        /**
         * Members of the annotation lineage as parent class identifiers.
         */
        id?: string;
        /**
         * Members of the annotation lineage as parent class names.
         */
        name?: string;
      }[];
    }[]
  ];
  rcsb_nonpolymer_entity_container_identifiers?: {
    asym_ids?: string[];
    auth_asym_ids?: string[];
    /**
     * The chemical reference definition identifier for the entity in this container.
     */
    chem_ref_def_id?: string;
    /**
     * Entity identifier for the container.
     */
    entity_id: string;
    /**
     * Entry identifier for the container.
     */
    entry_id: string;
    /**
     * Non-polymer(ligand) chemical component identifier for the entity in this container.
     */
    nonpolymer_comp_id?: string;
    /**
     * The BIRD identifier for the entity in this container.
     */
    prd_id?: string;
    /**
     * A unique identifier for each object in this entity container formed by
     *  an underscore separated concatenation of entry and entity identifiers.
     */
    rcsb_id?: string;
    reference_chemical_identifiers_provenance_source?: ("PDB" | "RCSB")[];
    reference_chemical_identifiers_resource_accession?: string[];
    reference_chemical_identifiers_resource_name?: ("ChEBI" | "ChEMBL" | "DrugBank" | "PubChem")[];
  };
  /**
   * @minItems 1
   */
  rcsb_nonpolymer_entity_feature?: [
    {
      /**
       * Identifies the version of the feature assignment.
       */
      assignment_version?: string;
      /**
       * Non-polymer(ligand) chemical component identifier for the entity.
       */
      comp_id?: string;
      /**
       * A description for the feature.
       */
      description?: string;
      /**
       * An identifier for the feature.
       */
      feature_id?: string;
      /**
       * A name for the feature.
       */
      name?: string;
      /**
       * Code identifying the individual, organization or program that
       *  assigned the feature.
       */
      provenance_source?: string;
      /**
       * A type or category of the feature.
       */
      type?: "SUBJECT_OF_INVESTIGATION";
      /**
       * The feature value.
       */
      value?: number;
      additional_properties?: {
        /**
         * The additional property name.
         */
        name?: string;
        values?: (string | number | number)[];
      }[];
    },
    ...{
      /**
       * Identifies the version of the feature assignment.
       */
      assignment_version?: string;
      /**
       * Non-polymer(ligand) chemical component identifier for the entity.
       */
      comp_id?: string;
      /**
       * A description for the feature.
       */
      description?: string;
      /**
       * An identifier for the feature.
       */
      feature_id?: string;
      /**
       * A name for the feature.
       */
      name?: string;
      /**
       * Code identifying the individual, organization or program that
       *  assigned the feature.
       */
      provenance_source?: string;
      /**
       * A type or category of the feature.
       */
      type?: "SUBJECT_OF_INVESTIGATION";
      /**
       * The feature value.
       */
      value?: number;
      additional_properties?: {
        /**
         * The additional property name.
         */
        name?: string;
        values?: (string | number | number)[];
      }[];
    }[]
  ];
  /**
   * @minItems 1
   */
  rcsb_nonpolymer_entity_feature_summary?: [
    {
      /**
       * Non-polymer(ligand) chemical component identifier for the entity.
       */
      comp_id?: string;
      /**
       * The feature count.
       */
      count?: number;
      /**
       * The maximum feature length.
       */
      maximum_length?: number;
      /**
       * The maximum feature value.
       */
      maximum_value?: number;
      /**
       * The minimum feature length.
       */
      minimum_length?: number;
      /**
       * The minimum feature value.
       */
      minimum_value?: number;
      /**
       * Type or category of the feature.
       */
      type?: "SUBJECT_OF_INVESTIGATION";
    },
    ...{
      /**
       * Non-polymer(ligand) chemical component identifier for the entity.
       */
      comp_id?: string;
      /**
       * The feature count.
       */
      count?: number;
      /**
       * The maximum feature length.
       */
      maximum_length?: number;
      /**
       * The maximum feature value.
       */
      maximum_value?: number;
      /**
       * The minimum feature length.
       */
      minimum_length?: number;
      /**
       * The minimum feature value.
       */
      minimum_value?: number;
      /**
       * Type or category of the feature.
       */
      type?: "SUBJECT_OF_INVESTIGATION";
    }[]
  ];
  rcsb_nonpolymer_entity_keywords?: {
    /**
     * Keywords describing this non-polymer entity.
     */
    text?: string;
  };
  /**
   * @minItems 1
   */
  rcsb_nonpolymer_entity_name_com?: [
    {
      /**
       * A common name for the nonpolymer entity.
       */
      name: string;
    },
    ...{
      /**
       * A common name for the nonpolymer entity.
       */
      name: string;
    }[]
  ];
  /**
   * A unique identifier for each object in this entity container formed by
   *  an underscore separated concatenation of entry and entity identifiers.
   */
  rcsb_id: string;
  rcsb_latest_revision?: {
    /**
     * The major version number of the latest revision.
     */
    major_revision?: number;
    /**
     * The minor version number of the latest revision.
     */
    minor_revision?: number;
    /**
     * The release date of the latest revision item.
     */
    revision_date?: string;
    [k: string]: unknown;
  };
}
