/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON schema for nonpolymer entity instance core.
 */
export interface CoreNonpolymerEntityInstance {
  /**
   * @minItems 1
   */
  pdbx_struct_special_symmetry?: [
    {
      /**
       * Part of the identifier for the molecular component.
       *
       * This data item is a pointer to _atom_site.pdbx_PDB_model_num in the
       * ATOM_SITE category.
       */
      PDB_model_num?: number;
      /**
       * Part of the identifier for the molecular component.
       *
       *  This data item is a pointer to _atom_site.auth_seq_id in the
       *  ATOM_SITE category.
       */
      auth_seq_id?: string;
      /**
       * The value of _pdbx_struct_special_symmetry.id must uniquely identify
       *  each item in the PDBX_STRUCT_SPECIAL_SYMMETRY list.
       *
       *  This is an integer serial number.
       */
      id: number;
      /**
       * Part of the identifier for the molecular component.
       *
       *  This data item is a pointer to _atom_site.label_asym_id in the
       *  ATOM_SITE category.
       */
      label_asym_id?: string;
      /**
       * Part of the identifier for the molecular component.
       *
       *  This data item is a pointer to _atom_site.label_comp_id in the
       *  ATOM_SITE category.
       */
      label_comp_id?: string;
    },
    ...{
      /**
       * Part of the identifier for the molecular component.
       *
       * This data item is a pointer to _atom_site.pdbx_PDB_model_num in the
       * ATOM_SITE category.
       */
      PDB_model_num?: number;
      /**
       * Part of the identifier for the molecular component.
       *
       *  This data item is a pointer to _atom_site.auth_seq_id in the
       *  ATOM_SITE category.
       */
      auth_seq_id?: string;
      /**
       * The value of _pdbx_struct_special_symmetry.id must uniquely identify
       *  each item in the PDBX_STRUCT_SPECIAL_SYMMETRY list.
       *
       *  This is an integer serial number.
       */
      id: number;
      /**
       * Part of the identifier for the molecular component.
       *
       *  This data item is a pointer to _atom_site.label_asym_id in the
       *  ATOM_SITE category.
       */
      label_asym_id?: string;
      /**
       * Part of the identifier for the molecular component.
       *
       *  This data item is a pointer to _atom_site.label_comp_id in the
       *  ATOM_SITE category.
       */
      label_comp_id?: string;
    }[]
  ];
  rcsb_nonpolymer_entity_instance_container_identifiers?: {
    /**
     * Instance identifier for this container.
     */
    asym_id: string;
    /**
     * Author instance identifier for this container.
     */
    auth_asym_id?: string;
    /**
     * Residue number for non-polymer entity instance.
     */
    auth_seq_id?: string;
    /**
     * Component identifier for non-polymer entity instance.
     */
    comp_id?: string;
    /**
     * Entity identifier for the container.
     */
    entity_id?: string;
    /**
     * Entry identifier for the container.
     */
    entry_id: string;
    /**
     * A unique identifier for each object in this entity instance container formed by
     *  an 'dot' (.) separated concatenation of entry and entity instance identifiers.
     */
    rcsb_id?: string;
  };
  /**
   * @minItems 1
   */
  rcsb_nonpolymer_instance_annotation?: [
    {
      /**
       * An identifier for the annotation.
       */
      annotation_id?: string;
      /**
       * Identifies the version of the annotation assignment.
       */
      assignment_version?: string;
      /**
       * Chemical component identifier.
       */
      comp_id?: string;
      /**
       * A description for the annotation.
       */
      description?: string;
      /**
       * A name for the annotation.
       */
      name?: string;
      /**
       * Ordinal identifier for this category
       */
      ordinal: number;
      /**
       * Code identifying the individual, organization or program that
       *  assigned the annotation.
       */
      provenance_source?: string;
      /**
       * A type or category of the annotation.
       */
      type?: "HAS_COVALENT_LINKAGE" | "HAS_METAL_COORDINATION_LINKAGE";
      annotation_lineage?: {
        /**
         * Members of the annotation lineage as parent lineage depth (1-N)
         */
        depth?: number;
        /**
         * Members of the annotation lineage as parent class identifiers.
         */
        id?: string;
        /**
         * Members of the annotation lineage as parent class names.
         */
        name?: string;
      }[];
    },
    ...{
      /**
       * An identifier for the annotation.
       */
      annotation_id?: string;
      /**
       * Identifies the version of the annotation assignment.
       */
      assignment_version?: string;
      /**
       * Chemical component identifier.
       */
      comp_id?: string;
      /**
       * A description for the annotation.
       */
      description?: string;
      /**
       * A name for the annotation.
       */
      name?: string;
      /**
       * Ordinal identifier for this category
       */
      ordinal: number;
      /**
       * Code identifying the individual, organization or program that
       *  assigned the annotation.
       */
      provenance_source?: string;
      /**
       * A type or category of the annotation.
       */
      type?: "HAS_COVALENT_LINKAGE" | "HAS_METAL_COORDINATION_LINKAGE";
      annotation_lineage?: {
        /**
         * Members of the annotation lineage as parent lineage depth (1-N)
         */
        depth?: number;
        /**
         * Members of the annotation lineage as parent class identifiers.
         */
        id?: string;
        /**
         * Members of the annotation lineage as parent class names.
         */
        name?: string;
      }[];
    }[]
  ];
  /**
   * @minItems 1
   */
  rcsb_nonpolymer_instance_feature?: [
    {
      /**
       * Identifies the version of the feature assignment.
       */
      assignment_version?: string;
      /**
       * Component identifier for non-polymer entity instance.
       */
      comp_id?: string;
      /**
       * A description for the feature.
       */
      description?: string;
      /**
       * An identifier for the feature.
       */
      feature_id?: string;
      /**
       * A name for the feature.
       */
      name?: string;
      /**
       * Ordinal identifier for this category
       */
      ordinal: number;
      /**
       * Code identifying the individual, organization or program that
       *  assigned the feature.
       */
      provenance_source?: string;
      /**
       * A type or category of the feature.
       */
      type?:
        | "HAS_COVALENT_LINKAGE"
        | "HAS_METAL_COORDINATION_LINKAGE"
        | "MOGUL_ANGLE_OUTLIER"
        | "MOGUL_BOND_OUTLIER"
        | "RSCC_OUTLIER"
        | "RSRZ_OUTLIER"
        | "STEREO_OUTLIER";
      feature_value?: {
        /**
         * The chemical component identifier for the instance of the feature value.
         */
        comp_id?: string;
        /**
         * Specific details about the feature.
         */
        details?: string;
        /**
         * The reference value of the feature.
         */
        reference?: number;
        /**
         * The reported value of the feature.
         */
        reported?: number;
        /**
         * The estimated uncertainty of the reported feature value.
         */
        uncertainty_estimate?: number;
        /**
         * The type of estimated uncertainty for the reported feature value.
         */
        uncertainty_estimate_type?: "Z-Score";
      }[];
      additional_properties?: {
        /**
         * The additional property name.
         */
        name?: string;
        values?: (string | number | number)[];
      }[];
    },
    ...{
      /**
       * Identifies the version of the feature assignment.
       */
      assignment_version?: string;
      /**
       * Component identifier for non-polymer entity instance.
       */
      comp_id?: string;
      /**
       * A description for the feature.
       */
      description?: string;
      /**
       * An identifier for the feature.
       */
      feature_id?: string;
      /**
       * A name for the feature.
       */
      name?: string;
      /**
       * Ordinal identifier for this category
       */
      ordinal: number;
      /**
       * Code identifying the individual, organization or program that
       *  assigned the feature.
       */
      provenance_source?: string;
      /**
       * A type or category of the feature.
       */
      type?:
        | "HAS_COVALENT_LINKAGE"
        | "HAS_METAL_COORDINATION_LINKAGE"
        | "MOGUL_ANGLE_OUTLIER"
        | "MOGUL_BOND_OUTLIER"
        | "RSCC_OUTLIER"
        | "RSRZ_OUTLIER"
        | "STEREO_OUTLIER";
      feature_value?: {
        /**
         * The chemical component identifier for the instance of the feature value.
         */
        comp_id?: string;
        /**
         * Specific details about the feature.
         */
        details?: string;
        /**
         * The reference value of the feature.
         */
        reference?: number;
        /**
         * The reported value of the feature.
         */
        reported?: number;
        /**
         * The estimated uncertainty of the reported feature value.
         */
        uncertainty_estimate?: number;
        /**
         * The type of estimated uncertainty for the reported feature value.
         */
        uncertainty_estimate_type?: "Z-Score";
      }[];
      additional_properties?: {
        /**
         * The additional property name.
         */
        name?: string;
        values?: (string | number | number)[];
      }[];
    }[]
  ];
  /**
   * @minItems 1
   */
  rcsb_nonpolymer_instance_feature_summary?: [
    {
      /**
       * Component identifier for non-polymer entity instance.
       */
      comp_id?: string;
      /**
       * The feature count.
       */
      count?: number;
      /**
       * The maximum feature length.
       */
      maximum_length?: number;
      /**
       * The maximum feature value.
       */
      maximum_value?: number;
      /**
       * The minimum feature length.
       */
      minimum_length?: number;
      /**
       * The minimum feature value.
       */
      minimum_value?: number;
      /**
       * Type or category of the feature.
       */
      type?:
        | "HAS_COVALENT_LINKAGE"
        | "HAS_METAL_COORDINATION_LINKAGE"
        | "MOGUL_ANGLE_OUTLIER"
        | "MOGUL_BOND_OUTLIER"
        | "RSCC_OUTLIER"
        | "RSRZ_OUTLIER"
        | "STEREO_OUTLIER";
    },
    ...{
      /**
       * Component identifier for non-polymer entity instance.
       */
      comp_id?: string;
      /**
       * The feature count.
       */
      count?: number;
      /**
       * The maximum feature length.
       */
      maximum_length?: number;
      /**
       * The maximum feature value.
       */
      maximum_value?: number;
      /**
       * The minimum feature length.
       */
      minimum_length?: number;
      /**
       * The minimum feature value.
       */
      minimum_value?: number;
      /**
       * Type or category of the feature.
       */
      type?:
        | "HAS_COVALENT_LINKAGE"
        | "HAS_METAL_COORDINATION_LINKAGE"
        | "MOGUL_ANGLE_OUTLIER"
        | "MOGUL_BOND_OUTLIER"
        | "RSCC_OUTLIER"
        | "RSRZ_OUTLIER"
        | "STEREO_OUTLIER";
    }[]
  ];
  /**
   * @minItems 1
   */
  rcsb_nonpolymer_instance_validation_score?: [
    {
      /**
       * The real space correlation coefficient (RSCC) for the non-polymer entity instance.
       */
      RSCC?: number;
      /**
       * The real space R-value (RSR) for the non-polymer entity instance.
       */
      RSR?: number;
      /**
       * Alternate conformer identifier for the non-polymer entity instance.
       */
      alt_id?: string;
      /**
       * The average heavy atom occupancy for coordinate records for the non-polymer entity instance.
       */
      average_occupancy?: number;
      /**
       * The reported fraction of atomic coordinate records for the non-polymer entity instance.
       */
      completeness?: number;
      /**
       * The number of intermolecular MolProbity clashes cacluated for reported atomic coordinate records.
       */
      intermolecular_clashes?: number;
      /**
       * This molecular instance is ranked as the best quality instance of this nonpolymer entity.
       */
      is_best_instance?: "N" | "Y";
      /**
       * This molecular entity is identified as the subject of the current study.
       */
      is_subject_of_investigation?: "N" | "Y";
      /**
       * The provenance for the selection of the molecular entity identified as the subject of the current study.
       */
      is_subject_of_investigation_provenance?: "Author" | "RCSB";
      /**
       * Number of bond angle outliers obtained from a CCDC Mogul survey of bond angles  in the CSD small
       *    molecule crystal structure database. Outliers are defined as bond angles that have a Z-score
       *    less than -2 or greater than 2.
       */
      mogul_angle_outliers?: number;
      /**
       * The root-mean-square value of the Z-scores of bond angles for the residue in degrees
       * obtained from a CCDC Mogul survey of bond angles in the CSD small molecule crystal structure database.
       */
      mogul_angles_RMSZ?: number;
      /**
       * Number of bond distance outliers obtained from a CCDC Mogul survey of bond lengths in the CSD small
       *    molecule crystal structure database.  Outliers are defined as bond distances that have a Z-score
       *    less than -2 or greater than 2.
       */
      mogul_bond_outliers?: number;
      /**
       * The root-mean-square value of the Z-scores of bond lengths for the residue in Angstroms
       * obtained from a CCDC Mogul survey of bond lengths in the CSD small molecule crystal structure database.
       */
      mogul_bonds_RMSZ?: number;
      /**
       * The ranking of the model fit score component.
       */
      ranking_model_fit?: number;
      /**
       * The ranking of the model geometry score component.
       */
      ranking_model_geometry?: number;
      /**
       * The value of the model fit score component.
       */
      score_model_fit?: number;
      /**
       * The value of the model geometry score component.
       */
      score_model_geometry?: number;
      /**
       * Number of stereochemical/chirality errors.
       */
      stereo_outliers?: number;
      /**
       * Score type.
       */
      type?: "RCSB_LIGAND_QUALITY_SCORE_2021";
    },
    ...{
      /**
       * The real space correlation coefficient (RSCC) for the non-polymer entity instance.
       */
      RSCC?: number;
      /**
       * The real space R-value (RSR) for the non-polymer entity instance.
       */
      RSR?: number;
      /**
       * Alternate conformer identifier for the non-polymer entity instance.
       */
      alt_id?: string;
      /**
       * The average heavy atom occupancy for coordinate records for the non-polymer entity instance.
       */
      average_occupancy?: number;
      /**
       * The reported fraction of atomic coordinate records for the non-polymer entity instance.
       */
      completeness?: number;
      /**
       * The number of intermolecular MolProbity clashes cacluated for reported atomic coordinate records.
       */
      intermolecular_clashes?: number;
      /**
       * This molecular instance is ranked as the best quality instance of this nonpolymer entity.
       */
      is_best_instance?: "N" | "Y";
      /**
       * This molecular entity is identified as the subject of the current study.
       */
      is_subject_of_investigation?: "N" | "Y";
      /**
       * The provenance for the selection of the molecular entity identified as the subject of the current study.
       */
      is_subject_of_investigation_provenance?: "Author" | "RCSB";
      /**
       * Number of bond angle outliers obtained from a CCDC Mogul survey of bond angles  in the CSD small
       *    molecule crystal structure database. Outliers are defined as bond angles that have a Z-score
       *    less than -2 or greater than 2.
       */
      mogul_angle_outliers?: number;
      /**
       * The root-mean-square value of the Z-scores of bond angles for the residue in degrees
       * obtained from a CCDC Mogul survey of bond angles in the CSD small molecule crystal structure database.
       */
      mogul_angles_RMSZ?: number;
      /**
       * Number of bond distance outliers obtained from a CCDC Mogul survey of bond lengths in the CSD small
       *    molecule crystal structure database.  Outliers are defined as bond distances that have a Z-score
       *    less than -2 or greater than 2.
       */
      mogul_bond_outliers?: number;
      /**
       * The root-mean-square value of the Z-scores of bond lengths for the residue in Angstroms
       * obtained from a CCDC Mogul survey of bond lengths in the CSD small molecule crystal structure database.
       */
      mogul_bonds_RMSZ?: number;
      /**
       * The ranking of the model fit score component.
       */
      ranking_model_fit?: number;
      /**
       * The ranking of the model geometry score component.
       */
      ranking_model_geometry?: number;
      /**
       * The value of the model fit score component.
       */
      score_model_fit?: number;
      /**
       * The value of the model geometry score component.
       */
      score_model_geometry?: number;
      /**
       * Number of stereochemical/chirality errors.
       */
      stereo_outliers?: number;
      /**
       * Score type.
       */
      type?: "RCSB_LIGAND_QUALITY_SCORE_2021";
    }[]
  ];
  /**
   * @minItems 1
   */
  rcsb_nonpolymer_struct_conn?: [
    {
      /**
       * The connection type.
       */
      connect_type?:
        | "covalent bond"
        | "disulfide bridge"
        | "hydrogen bond"
        | "ionic interaction"
        | "metal coordination"
        | "mismatched base pairs";
      /**
       * A description of special details of the connection.
       */
      description?: string;
      /**
       * Distance value for this contact.
       */
      dist_value?: number;
      /**
       * The value of _rcsb_nonpolymer_struct_conn.id is an identifier for connection.
       *
       *  Note that this item need not be a number; it can be any unique
       *  identifier.
       */
      id?: string;
      /**
       * The value of _rcsb_nonpolymer_struct_conn.id must uniquely identify a record in
       *  the rcsb_nonpolymer_struct_conn list.
       */
      ordinal_id: number;
      /**
       * The chemical or structural role of the interaction
       */
      role?: "C-Mannosylation" | "N-Glycosylation" | "O-Glycosylation" | "S-Glycosylation";
      /**
       * The chemical bond order associated with the specified atoms in
       *  this contact.
       */
      value_order?: "doub" | "quad" | "sing" | "trip";
      connect_target?: {
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.auth_asym_id in the
         *  ATOM_SITE category.
         */
        auth_asym_id?: string;
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.auth_seq_id in the
         *  ATOM_SITE category.
         */
        auth_seq_id?: string;
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_alt_id in the
         *  ATOM_SITE category.
         */
        label_alt_id?: string;
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_asym_id in the
         *  ATOM_SITE category.
         */
        label_asym_id: string;
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_atom_id in the
         *  ATOM_SITE category.
         */
        label_atom_id?: string;
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_comp_id in the
         *  ATOM_SITE category.
         */
        label_comp_id: string;
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.connect_target_label_seq_id in the
         *  ATOM_SITE category.
         */
        label_seq_id?: number;
        /**
         * Describes the symmetry operation that should be applied to the
         *  atom set specified by _rcsb_nonpolymer_struct_conn.label* to generate the
         *  target of the structure connection.
         */
        symmetry?: string;
      };
      connect_partner?: {
        /**
         * A component of the identifier for the partner in the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_alt_id in the
         *  ATOM_SITE category.
         */
        label_alt_id?: string;
        /**
         * A component of the identifier for the partner in the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_asym_id in the
         *  ATOM_SITE category.
         */
        label_asym_id: string;
        /**
         * A component of the identifier for the partner in the structure
         *  connection.
         *
         *  This data item is a pointer to _chem_comp_atom.atom_id in the
         *  CHEM_COMP_ATOM category.
         */
        label_atom_id?: string;
        /**
         * A component of the identifier for the partner in the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_comp_id in the
         *  ATOM_SITE category.
         */
        label_comp_id: string;
        /**
         * A component of the identifier for the partner in the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_seq_id in the
         *  ATOM_SITE category.
         */
        label_seq_id?: number;
        /**
         * Describes the symmetry operation that should be applied to the
         *  atom set specified by _rcsb_nonpolymer_struct_conn.connect_partner_label* to generate the
         *  partner in the structure connection.
         */
        symmetry?: string;
      };
    },
    ...{
      /**
       * The connection type.
       */
      connect_type?:
        | "covalent bond"
        | "disulfide bridge"
        | "hydrogen bond"
        | "ionic interaction"
        | "metal coordination"
        | "mismatched base pairs";
      /**
       * A description of special details of the connection.
       */
      description?: string;
      /**
       * Distance value for this contact.
       */
      dist_value?: number;
      /**
       * The value of _rcsb_nonpolymer_struct_conn.id is an identifier for connection.
       *
       *  Note that this item need not be a number; it can be any unique
       *  identifier.
       */
      id?: string;
      /**
       * The value of _rcsb_nonpolymer_struct_conn.id must uniquely identify a record in
       *  the rcsb_nonpolymer_struct_conn list.
       */
      ordinal_id: number;
      /**
       * The chemical or structural role of the interaction
       */
      role?: "C-Mannosylation" | "N-Glycosylation" | "O-Glycosylation" | "S-Glycosylation";
      /**
       * The chemical bond order associated with the specified atoms in
       *  this contact.
       */
      value_order?: "doub" | "quad" | "sing" | "trip";
      connect_target?: {
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.auth_asym_id in the
         *  ATOM_SITE category.
         */
        auth_asym_id?: string;
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.auth_seq_id in the
         *  ATOM_SITE category.
         */
        auth_seq_id?: string;
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_alt_id in the
         *  ATOM_SITE category.
         */
        label_alt_id?: string;
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_asym_id in the
         *  ATOM_SITE category.
         */
        label_asym_id: string;
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_atom_id in the
         *  ATOM_SITE category.
         */
        label_atom_id?: string;
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_comp_id in the
         *  ATOM_SITE category.
         */
        label_comp_id: string;
        /**
         * A component of the identifier for the target of the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.connect_target_label_seq_id in the
         *  ATOM_SITE category.
         */
        label_seq_id?: number;
        /**
         * Describes the symmetry operation that should be applied to the
         *  atom set specified by _rcsb_nonpolymer_struct_conn.label* to generate the
         *  target of the structure connection.
         */
        symmetry?: string;
      };
      connect_partner?: {
        /**
         * A component of the identifier for the partner in the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_alt_id in the
         *  ATOM_SITE category.
         */
        label_alt_id?: string;
        /**
         * A component of the identifier for the partner in the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_asym_id in the
         *  ATOM_SITE category.
         */
        label_asym_id: string;
        /**
         * A component of the identifier for the partner in the structure
         *  connection.
         *
         *  This data item is a pointer to _chem_comp_atom.atom_id in the
         *  CHEM_COMP_ATOM category.
         */
        label_atom_id?: string;
        /**
         * A component of the identifier for the partner in the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_comp_id in the
         *  ATOM_SITE category.
         */
        label_comp_id: string;
        /**
         * A component of the identifier for the partner in the structure
         *  connection.
         *
         *  This data item is a pointer to _atom_site.label_seq_id in the
         *  ATOM_SITE category.
         */
        label_seq_id?: number;
        /**
         * Describes the symmetry operation that should be applied to the
         *  atom set specified by _rcsb_nonpolymer_struct_conn.connect_partner_label* to generate the
         *  partner in the structure connection.
         */
        symmetry?: string;
      };
    }[]
  ];
  /**
   * @minItems 1
   */
  rcsb_target_neighbors?: [
    {
      /**
       * Alternate conformer identifier for the non-polymer entity instance.
       */
      alt_id?: string;
      /**
       * The atom identifier for the non-polymer entity instance.
       */
      atom_id?: string;
      /**
       * Component identifier for the non-polymer entity instance.
       */
      comp_id?: string;
      /**
       * Distance value for this target interaction.
       */
      distance?: number;
      /**
       * The entity instance identifier for the target of interaction.
       */
      target_asym_id?: string;
      /**
       * The atom identifier for the target of interaction.
       */
      target_atom_id?: string;
      /**
       * The author residue index for the target of interaction.
       */
      target_auth_seq_id?: number;
      /**
       * The chemical component identifier for the target of interaction.
       */
      target_comp_id?: string;
      /**
       * The entity identifier for the target of interaction.
       */
      target_entity_id?: string;
      /**
       * A flag to indicate the nature of the target interaction is covalent or metal-coordination.
       */
      target_is_bound?: "N" | "Y";
      /**
       * Model identifier for the target of interaction.
       */
      target_model_id?: number;
      /**
       * The sequence position for the target of interaction.
       */
      target_seq_id?: number;
    },
    ...{
      /**
       * Alternate conformer identifier for the non-polymer entity instance.
       */
      alt_id?: string;
      /**
       * The atom identifier for the non-polymer entity instance.
       */
      atom_id?: string;
      /**
       * Component identifier for the non-polymer entity instance.
       */
      comp_id?: string;
      /**
       * Distance value for this target interaction.
       */
      distance?: number;
      /**
       * The entity instance identifier for the target of interaction.
       */
      target_asym_id?: string;
      /**
       * The atom identifier for the target of interaction.
       */
      target_atom_id?: string;
      /**
       * The author residue index for the target of interaction.
       */
      target_auth_seq_id?: number;
      /**
       * The chemical component identifier for the target of interaction.
       */
      target_comp_id?: string;
      /**
       * The entity identifier for the target of interaction.
       */
      target_entity_id?: string;
      /**
       * A flag to indicate the nature of the target interaction is covalent or metal-coordination.
       */
      target_is_bound?: "N" | "Y";
      /**
       * Model identifier for the target of interaction.
       */
      target_model_id?: number;
      /**
       * The sequence position for the target of interaction.
       */
      target_seq_id?: number;
    }[]
  ];
  /**
   * A unique identifier for each object in this entity instance container formed by
   *  an 'dot' (.) separated concatenation of entry and entity instance identifiers.
   */
  rcsb_id: string;
  rcsb_latest_revision?: {
    /**
     * The major version number of the latest revision.
     */
    major_revision?: number;
    /**
     * The minor version number of the latest revision.
     */
    minor_revision?: number;
    /**
     * The release date of the latest revision item.
     */
    revision_date?: string;
    [k: string]: unknown;
  };
}
