/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * RCSB Exchange Database JSON schema derived from the drugbank_core content type schema. This schema supports collection drugbank_core version 1.3.2. This schema is hosted in repository https://github.com/rcsb/py-rcsb.db/tree/master/rcsb.db/data/json-schema/json-schema-min-drugbank_core.json and follows JSON schema specification version 4
 */
export interface SchemaDrugbankCoreCollectionDrugbankCoreVersion132 {
  drugbank_container_identifiers?: {
    /**
     * The DrugBank accession code
     */
    drugbank_id: string;
  };
  drugbank_info?: {
    affected_organisms?: string[];
    atc_codes?: string[];
    brand_names?: string[];
    /**
     * The DrugBank assigned Chemical Abstracts Service identifier.
     */
    cas_number?: string;
    /**
     * The DrugBank drug description.
     */
    description?: string;
    drug_categories?: string[];
    drug_groups?: string[];
    /**
     * The DrugBank accession code
     */
    drugbank_id: string;
    /**
     * The DrugBank drug indication.
     */
    indication?: string;
    /**
     * The DrugBank drug mechanism of actions.
     */
    mechanism_of_action?: string;
    /**
     * The DrugBank drug name.
     */
    name?: string;
    /**
     * The DrugBank drug pharmacology.
     */
    pharmacology?: string;
    synonyms?: string[];
  };
  /**
   * @minItems 1
   */
  drugbank_target?: [
    {
      /**
       * The type of target interaction.
       */
      interaction_type?: string;
      /**
       * The target name.
       */
      name?: string;
      /**
       * The value of _drugbank_target.ordinal distinguishes
       *  related examples for each chemical component.
       */
      ordinal: number;
      /**
       * The organism common name.
       */
      organism_common_name?: string;
      /**
       * The reference identifier code for the target interaction reference.
       */
      reference_database_accession_code?: string;
      /**
       * The reference database name for the target interaction.
       */
      reference_database_name?: "UniProt";
      /**
       * Target sequence expressed as string of one-letter amino acid codes.
       */
      seq_one_letter_code?: string;
      target_actions?: string[];
    },
    ...{
      /**
       * The type of target interaction.
       */
      interaction_type?: string;
      /**
       * The target name.
       */
      name?: string;
      /**
       * The value of _drugbank_target.ordinal distinguishes
       *  related examples for each chemical component.
       */
      ordinal: number;
      /**
       * The organism common name.
       */
      organism_common_name?: string;
      /**
       * The reference identifier code for the target interaction reference.
       */
      reference_database_accession_code?: string;
      /**
       * The reference database name for the target interaction.
       */
      reference_database_name?: "UniProt";
      /**
       * Target sequence expressed as string of one-letter amino acid codes.
       */
      seq_one_letter_code?: string;
      target_actions?: string[];
    }[]
  ];
}
