/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * RCSB Exchange Database JSON schema derived from the bird_chem_comp_core content type schema. This schema supports collection bird_chem_comp_core version 7.1.2. This schema is hosted in repository https://github.com/rcsb/py-rcsb.db/tree/master/rcsb.db/data/json-schema/json-schema-min-bird_chem_comp_core.json and follows JSON schema specification version 4
 */
export interface SchemaBirdChemCompCoreCollectionBirdChemCompCoreVersion712 {
  chem_comp?: {
    /**
     * The formula for the chemical component. Formulae are written
     *  according to the following rules:
     *
     *  (1) Only recognized element symbols may be used.
     *
     *  (2) Each element symbol is followed by a 'count' number. A count
     *     of '1' may be omitted.
     *
     *  (3) A space or parenthesis must separate each cluster of
     *     (element symbol + count), but in general parentheses are
     *     not used.
     *
     *  (4) The order of elements depends on whether carbon is
     *     present or not. If carbon is present, the order should be:
     *     C, then H, then the other elements in alphabetical order
     *     of their symbol. If carbon is not present, the elements
     *     are listed purely in alphabetic order of their symbol. This
     *     is the 'Hill' system used by Chemical Abstracts.
     */
    formula?: string;
    /**
     * Formula mass of the chemical component.
     */
    formula_weight?: number;
    /**
     * The value of _chem_comp.id must uniquely identify each item in
     *  the CHEM_COMP list.
     *
     *  For protein polymer entities, this is the three-letter code for
     *  the amino acid.
     *
     *  For nucleic acid polymer entities, this is the one-letter code
     *  for the base.
     */
    id: string;
    mon_nstd_parent_comp_id?: string[];
    /**
     * The full name of the component.
     */
    name?: string;
    /**
     * For standard polymer components, the one-letter code for
     *  the component.   For non-standard polymer components, the
     *  one-letter code for parent component if this exists;
     *  otherwise, the one-letter code should be given as 'X'.
     *
     *  Components that derived from multiple parents components
     *  are described by a sequence of one-letter-codes.
     */
    one_letter_code?: string;
    /**
     * A preliminary classification used by PDB to indicate
     *  that the chemistry of this component while described
     *  as clearly as possible is still ambiguous.  Software
     *  tools may not be able to process this component
     *  definition.
     */
    pdbx_ambiguous_flag?: string;
    /**
     * The net integer charge assigned to this component. This is the
     *  formal charge assignment normally found in chemical diagrams.
     */
    pdbx_formal_charge?: number;
    /**
     * Date component was added to database.
     */
    pdbx_initial_date?: string;
    /**
     * Date component was last modified.
     */
    pdbx_modified_date?: string;
    /**
     * This data item identifies the deposition site that processed
     *  this chemical component defintion.
     */
    pdbx_processing_site?: "EBI" | "PDBC" | "PDBE" | "PDBJ" | "RCSB";
    /**
     * This data item holds the current release status for the component.
     */
    pdbx_release_status?: "DEL" | "HOLD" | "HPUB" | "OBS" | "REF_ONLY" | "REL";
    /**
     * Identifies the _chem_comp.id of the component that
     *  has replaced this component.
     */
    pdbx_replaced_by?: string;
    /**
     * Identifies the _chem_comp.id's of the components
     *  which have been replaced by this component.
     *  Multiple id codes should be separated by commas.
     */
    pdbx_replaces?: string;
    /**
     * The list of subcomponents contained in this component.
     */
    pdbx_subcomponent_list?: string;
    /**
     * For standard polymer components, the common three-letter code for
     *  the component.   Non-standard polymer components and non-polymer
     *  components are also assigned three-letter-codes.
     *
     *  For ambiguous polymer components three-letter code should
     *  be given as 'UNK'.  Ambiguous ions are assigned the code 'UNX'.
     *  Ambiguous non-polymer components are assigned the code 'UNL'.
     */
    three_letter_code?: string;
    /**
     * For standard polymer components, the type of the monomer.
     *  Note that monomers that will form polymers are of three types:
     *  linking monomers, monomers with some type of N-terminal (or 5')
     *  cap and monomers with some type of C-terminal (or 3') cap.
     */
    type?:
      | "D-beta-peptide, C-gamma linking"
      | "D-gamma-peptide, C-delta linking"
      | "D-peptide COOH carboxy terminus"
      | "D-peptide NH3 amino terminus"
      | "D-peptide linking"
      | "D-saccharide"
      | "D-saccharide, alpha linking"
      | "D-saccharide, beta linking"
      | "DNA OH 3 prime terminus"
      | "DNA OH 5 prime terminus"
      | "DNA linking"
      | "L-DNA linking"
      | "L-RNA linking"
      | "L-beta-peptide, C-gamma linking"
      | "L-gamma-peptide, C-delta linking"
      | "L-peptide COOH carboxy terminus"
      | "L-peptide NH3 amino terminus"
      | "L-peptide linking"
      | "L-saccharide"
      | "L-saccharide, alpha linking"
      | "L-saccharide, beta linking"
      | "RNA OH 3 prime terminus"
      | "RNA OH 5 prime terminus"
      | "RNA linking"
      | "non-polymer"
      | "other"
      | "peptide linking"
      | "peptide-like"
      | "saccharide";
  };
  /**
   * @minItems 1
   */
  pdbx_chem_comp_audit?: [
    {
      /**
       * The action associated with this audit record.
       */
      action_type?:
        | "Create component"
        | "Initial release"
        | "Modify aromatic_flag"
        | "Modify atom id"
        | "Modify charge"
        | "Modify component atom id"
        | "Modify component comp_id"
        | "Modify coordinates"
        | "Modify descriptor"
        | "Modify formal charge"
        | "Modify formula"
        | "Modify identifier"
        | "Modify internal type"
        | "Modify leaving atom flag"
        | "Modify linking type"
        | "Modify model coordinates code"
        | "Modify name"
        | "Modify one letter code"
        | "Modify parent residue"
        | "Modify processing site"
        | "Modify subcomponent list"
        | "Modify synonyms"
        | "Modify value order"
        | "Obsolete component"
        | "Other modification";
      /**
       * This data item is a pointer to _chem_comp.id in the CHEM_COMP
       *  category.
       */
      comp_id?: string;
      /**
       * The date associated with this audit record.
       */
      date?: string;
      /**
       * Additional details decribing this change.
       */
      details?: string;
      /**
       * This data item is an ordinal index for the
       *  PDBX_CHEM_COMP_AUDIT category.
       */
      ordinal: number;
    },
    ...{
      /**
       * The action associated with this audit record.
       */
      action_type?:
        | "Create component"
        | "Initial release"
        | "Modify aromatic_flag"
        | "Modify atom id"
        | "Modify charge"
        | "Modify component atom id"
        | "Modify component comp_id"
        | "Modify coordinates"
        | "Modify descriptor"
        | "Modify formal charge"
        | "Modify formula"
        | "Modify identifier"
        | "Modify internal type"
        | "Modify leaving atom flag"
        | "Modify linking type"
        | "Modify model coordinates code"
        | "Modify name"
        | "Modify one letter code"
        | "Modify parent residue"
        | "Modify processing site"
        | "Modify subcomponent list"
        | "Modify synonyms"
        | "Modify value order"
        | "Obsolete component"
        | "Other modification";
      /**
       * This data item is a pointer to _chem_comp.id in the CHEM_COMP
       *  category.
       */
      comp_id?: string;
      /**
       * The date associated with this audit record.
       */
      date?: string;
      /**
       * Additional details decribing this change.
       */
      details?: string;
      /**
       * This data item is an ordinal index for the
       *  PDBX_CHEM_COMP_AUDIT category.
       */
      ordinal: number;
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_chem_comp_descriptor?: [
    {
      /**
       * This data item is a pointer to _chem_comp.id in the CHEM_COMP
       *  category.
       */
      comp_id: string;
      /**
       * This data item contains the descriptor value for this
       *  component.
       */
      descriptor?: string;
      /**
       * This data item contains the name of the program
       *  or library used to compute the descriptor.
       */
      program: string;
      /**
       * This data item contains the version of the program
       *  or library used to compute the descriptor.
       */
      program_version: string;
      /**
       * This data item contains the descriptor type.
       */
      type:
        | "InChI"
        | "InChIKey"
        | "InChI_CHARGE"
        | "InChI_FIXEDH"
        | "InChI_ISOTOPE"
        | "InChI_MAIN"
        | "InChI_MAIN_CONNECT"
        | "InChI_MAIN_FORMULA"
        | "InChI_MAIN_HATOM"
        | "InChI_RECONNECT"
        | "InChI_STEREO"
        | "SMILES"
        | "SMILES_CANNONICAL"
        | "SMILES_CANONICAL";
    },
    ...{
      /**
       * This data item is a pointer to _chem_comp.id in the CHEM_COMP
       *  category.
       */
      comp_id: string;
      /**
       * This data item contains the descriptor value for this
       *  component.
       */
      descriptor?: string;
      /**
       * This data item contains the name of the program
       *  or library used to compute the descriptor.
       */
      program: string;
      /**
       * This data item contains the version of the program
       *  or library used to compute the descriptor.
       */
      program_version: string;
      /**
       * This data item contains the descriptor type.
       */
      type:
        | "InChI"
        | "InChIKey"
        | "InChI_CHARGE"
        | "InChI_FIXEDH"
        | "InChI_ISOTOPE"
        | "InChI_MAIN"
        | "InChI_MAIN_CONNECT"
        | "InChI_MAIN_FORMULA"
        | "InChI_MAIN_HATOM"
        | "InChI_RECONNECT"
        | "InChI_STEREO"
        | "SMILES"
        | "SMILES_CANNONICAL"
        | "SMILES_CANONICAL";
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_chem_comp_feature?: [
    {
      /**
       * The component identifier for this feature.
       */
      comp_id: string;
      /**
       * The information source for the component feature.
       */
      source: string;
      /**
       * The component feature type.
       */
      type: "CARBOHYDRATE ANOMER" | "CARBOHYDRATE ISOMER" | "CARBOHYDRATE PRIMARY CARBONYL GROUP" | "CARBOHYDRATE RING";
      /**
       * The component feature value.
       */
      value: string;
    },
    ...{
      /**
       * The component identifier for this feature.
       */
      comp_id: string;
      /**
       * The information source for the component feature.
       */
      source: string;
      /**
       * The component feature type.
       */
      type: "CARBOHYDRATE ANOMER" | "CARBOHYDRATE ISOMER" | "CARBOHYDRATE PRIMARY CARBONYL GROUP" | "CARBOHYDRATE RING";
      /**
       * The component feature value.
       */
      value: string;
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_chem_comp_identifier?: [
    {
      /**
       * This data item is a pointer to _chem_comp.id in the CHEM_COMP
       *  category.
       */
      comp_id: string;
      /**
       * This data item contains the identifier value for this
       *  component.
       */
      identifier?: string;
      /**
       * This data item contains the name of the program
       *  or library used to compute the identifier.
       */
      program: string;
      /**
       * This data item contains the version of the program
       *  or library used to compute the identifier.
       */
      program_version: string;
      /**
       * This data item contains the identifier type.
       */
      type:
        | "CAS REGISTRY NUMBER"
        | "COMMON NAME"
        | "CONDENSED IUPAC CARB SYMBOL"
        | "CONDENSED IUPAC CARBOHYDRATE SYMBOL"
        | "IUPAC CARB SYMBOL"
        | "IUPAC CARBOHYDRATE SYMBOL"
        | "MDL Identifier"
        | "PUBCHEM Identifier"
        | "SNFG CARB SYMBOL"
        | "SNFG CARBOHYDRATE SYMBOL"
        | "SYNONYM"
        | "SYSTEMATIC NAME";
    },
    ...{
      /**
       * This data item is a pointer to _chem_comp.id in the CHEM_COMP
       *  category.
       */
      comp_id: string;
      /**
       * This data item contains the identifier value for this
       *  component.
       */
      identifier?: string;
      /**
       * This data item contains the name of the program
       *  or library used to compute the identifier.
       */
      program: string;
      /**
       * This data item contains the version of the program
       *  or library used to compute the identifier.
       */
      program_version: string;
      /**
       * This data item contains the identifier type.
       */
      type:
        | "CAS REGISTRY NUMBER"
        | "COMMON NAME"
        | "CONDENSED IUPAC CARB SYMBOL"
        | "CONDENSED IUPAC CARBOHYDRATE SYMBOL"
        | "IUPAC CARB SYMBOL"
        | "IUPAC CARBOHYDRATE SYMBOL"
        | "MDL Identifier"
        | "PUBCHEM Identifier"
        | "SNFG CARB SYMBOL"
        | "SNFG CARBOHYDRATE SYMBOL"
        | "SYNONYM"
        | "SYSTEMATIC NAME";
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_family_prd_audit?: [
    {
      /**
       * The action associated with this audit record.
       */
      action_type:
        | "Add PRD"
        | "Create family"
        | "Initial release"
        | "Modify annotation"
        | "Modify citation"
        | "Modify family classification"
        | "Modify family name"
        | "Modify feature"
        | "Modify molecule details"
        | "Modify related structures"
        | "Modify sequence"
        | "Modify synonyms"
        | "Obsolete family"
        | "Obsolete familyt"
        | "Other modification"
        | "Remove PRD";
      /**
       * The initials of the annotator creating of modifying the family.
       */
      annotator?: string;
      /**
       * The date associated with this audit record.
       */
      date: string;
      /**
       * Additional details decribing this change.
       */
      details?: string;
      /**
       * This data item is a pointer to _pdbx_reference_molecule_family.family_prd_id in the
       * 	       pdbx_reference_molecule category.
       */
      family_prd_id: string;
      /**
       * An identifier for the wwPDB site creating or modifying the family.
       */
      processing_site?: string;
    },
    ...{
      /**
       * The action associated with this audit record.
       */
      action_type:
        | "Add PRD"
        | "Create family"
        | "Initial release"
        | "Modify annotation"
        | "Modify citation"
        | "Modify family classification"
        | "Modify family name"
        | "Modify feature"
        | "Modify molecule details"
        | "Modify related structures"
        | "Modify sequence"
        | "Modify synonyms"
        | "Obsolete family"
        | "Obsolete familyt"
        | "Other modification"
        | "Remove PRD";
      /**
       * The initials of the annotator creating of modifying the family.
       */
      annotator?: string;
      /**
       * The date associated with this audit record.
       */
      date: string;
      /**
       * Additional details decribing this change.
       */
      details?: string;
      /**
       * This data item is a pointer to _pdbx_reference_molecule_family.family_prd_id in the
       * 	       pdbx_reference_molecule category.
       */
      family_prd_id: string;
      /**
       * An identifier for the wwPDB site creating or modifying the family.
       */
      processing_site?: string;
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_prd_audit?: [
    {
      /**
       * The action associated with this audit record.
       */
      action_type:
        | "Create molecule"
        | "Initial release"
        | "Modify audit"
        | "Modify class"
        | "Modify linkage"
        | "Modify molecule name"
        | "Modify representation"
        | "Modify sequence"
        | "Modify taxonomy organism"
        | "Modify type"
        | "Obsolete molecule"
        | "Other modification";
      /**
       * The initials of the annotator creating of modifying the molecule.
       */
      annotator?: string;
      /**
       * The date associated with this audit record.
       */
      date: string;
      /**
       * Additional details decribing this change.
       */
      details?: string;
      /**
       * This data item is a pointer to _pdbx_reference_molecule.prd_id in the
       * 	       pdbx_reference_molecule category.
       */
      prd_id: string;
      /**
       * An identifier for the wwPDB site creating or modifying the molecule.
       */
      processing_site?: "BMRB" | "PDBC" | "PDBE" | "PDBJ" | "RCSB";
    },
    ...{
      /**
       * The action associated with this audit record.
       */
      action_type:
        | "Create molecule"
        | "Initial release"
        | "Modify audit"
        | "Modify class"
        | "Modify linkage"
        | "Modify molecule name"
        | "Modify representation"
        | "Modify sequence"
        | "Modify taxonomy organism"
        | "Modify type"
        | "Obsolete molecule"
        | "Other modification";
      /**
       * The initials of the annotator creating of modifying the molecule.
       */
      annotator?: string;
      /**
       * The date associated with this audit record.
       */
      date: string;
      /**
       * Additional details decribing this change.
       */
      details?: string;
      /**
       * This data item is a pointer to _pdbx_reference_molecule.prd_id in the
       * 	       pdbx_reference_molecule category.
       */
      prd_id: string;
      /**
       * An identifier for the wwPDB site creating or modifying the molecule.
       */
      processing_site?: "BMRB" | "PDBC" | "PDBE" | "PDBJ" | "RCSB";
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_reference_entity_list?: [
    {
      /**
       * The component number of this entity within the molecule.
       */
      component_id: number;
      /**
       * Additional details about this entity.
       */
      details?: string;
      /**
       * The value of _pdbx_reference_entity_list.prd_id is a reference
       *  _pdbx_reference_molecule.prd_id in the PDBX_REFERENCE_MOLECULE category.
       */
      prd_id: string;
      /**
       * The value of _pdbx_reference_entity_list.ref_entity_id is a unique identifier
       *  the a constituent entity within this reference molecule.
       */
      ref_entity_id: string;
      /**
       * Defines the polymer characteristic of the entity.
       */
      type?: "branched" | "non-polymer" | "polymer" | "polymer-like";
    },
    ...{
      /**
       * The component number of this entity within the molecule.
       */
      component_id: number;
      /**
       * Additional details about this entity.
       */
      details?: string;
      /**
       * The value of _pdbx_reference_entity_list.prd_id is a reference
       *  _pdbx_reference_molecule.prd_id in the PDBX_REFERENCE_MOLECULE category.
       */
      prd_id: string;
      /**
       * The value of _pdbx_reference_entity_list.ref_entity_id is a unique identifier
       *  the a constituent entity within this reference molecule.
       */
      ref_entity_id: string;
      /**
       * Defines the polymer characteristic of the entity.
       */
      type?: "branched" | "non-polymer" | "polymer" | "polymer-like";
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_reference_entity_poly?: [
    {
      /**
       * The database code for this source information
       */
      db_code?: string;
      /**
       * The database name for this source information
       */
      db_name?: string;
      /**
       * The value of _pdbx_reference_entity_poly.prd_id is a reference
       * 	       _pdbx_reference_entity_list.prd_id in the  PDBX_REFERENCE_ENTITY_LIST category.
       */
      prd_id: string;
      /**
       * The value of _pdbx_reference_entity_poly.ref_entity_id is a reference
       *  to _pdbx_reference_entity_list.ref_entity_id in PDBX_REFERENCE_ENTITY_LIST category.
       */
      ref_entity_id: string;
      /**
       * The type of the polymer.
       */
      type?: "nucleic-acid-like" | "oligosaccharide" | "peptide-like" | "polysaccharide-like";
    },
    ...{
      /**
       * The database code for this source information
       */
      db_code?: string;
      /**
       * The database name for this source information
       */
      db_name?: string;
      /**
       * The value of _pdbx_reference_entity_poly.prd_id is a reference
       * 	       _pdbx_reference_entity_list.prd_id in the  PDBX_REFERENCE_ENTITY_LIST category.
       */
      prd_id: string;
      /**
       * The value of _pdbx_reference_entity_poly.ref_entity_id is a reference
       *  to _pdbx_reference_entity_list.ref_entity_id in PDBX_REFERENCE_ENTITY_LIST category.
       */
      ref_entity_id: string;
      /**
       * The type of the polymer.
       */
      type?: "nucleic-acid-like" | "oligosaccharide" | "peptide-like" | "polysaccharide-like";
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_reference_entity_poly_link?: [
    {
      /**
       * The atom identifier/name in the first of the two components making
       *  the linkage.
       */
      atom_id_1?: string;
      /**
       * The atom identifier/name in the second of the two components making
       *  the linkage.
       */
      atom_id_2?: string;
      /**
       * The component identifier in the first of the two components making the
       *  linkage.
       *
       *  This data item is a pointer to _pdbx_reference_entity_poly_seq.mon_id
       *  in the PDBX_REFERENCE_ENTITY_POLY_SEQ category.
       */
      comp_id_1?: string;
      /**
       * The component identifier in the second of the two components making the
       *  linkage.
       *
       *  This data item is a pointer to _pdbx_reference_entity_poly_seq.mon_id
       *  in the PDBX_REFERENCE_ENTITY_POLY_SEQ category.
       */
      comp_id_2?: string;
      /**
       * The entity component identifier entity containing the linkage.
       */
      component_id: number;
      /**
       * For a polymer entity, the sequence number in the first of
       *  the two components making the linkage.
       *
       *  This data item is a pointer to _pdbx_reference_entity_poly_seq.num
       *  in the PDBX_REFERENCE_ENTITY_POLY_SEQ category.
       */
      entity_seq_num_1?: number;
      /**
       * For a polymer entity, the sequence number in the second of
       *  the two components making the linkage.
       *
       *  This data item is a pointer to _pdbx_reference_entity_poly_seq.num
       *  in the PDBX_REFERENCE_ENTITY_POLY_SEQ category.
       */
      entity_seq_num_2?: number;
      /**
       * The value of _pdbx_reference_entity_poly_link.link_id uniquely identifies
       *  a linkage within a polymer entity.
       */
      link_id: number;
      /**
       * The value of _pdbx_reference_entity_poly_link.prd_id is a reference
       *  _pdbx_reference_entity_list.prd_id in the PDBX_REFERENCE_ENTITY_POLY category.
       */
      prd_id: string;
      /**
       * The reference entity id of the polymer entity containing the linkage.
       *
       *  This data item is a pointer to _pdbx_reference_entity_poly.ref_entity_id
       *  in the PDBX_REFERENCE_ENTITY_POLY category.
       */
      ref_entity_id: string;
      /**
       * The bond order target for the non-standard linkage.
       */
      value_order?: "arom" | "delo" | "doub" | "pi" | "poly" | "quad" | "sing" | "trip";
    },
    ...{
      /**
       * The atom identifier/name in the first of the two components making
       *  the linkage.
       */
      atom_id_1?: string;
      /**
       * The atom identifier/name in the second of the two components making
       *  the linkage.
       */
      atom_id_2?: string;
      /**
       * The component identifier in the first of the two components making the
       *  linkage.
       *
       *  This data item is a pointer to _pdbx_reference_entity_poly_seq.mon_id
       *  in the PDBX_REFERENCE_ENTITY_POLY_SEQ category.
       */
      comp_id_1?: string;
      /**
       * The component identifier in the second of the two components making the
       *  linkage.
       *
       *  This data item is a pointer to _pdbx_reference_entity_poly_seq.mon_id
       *  in the PDBX_REFERENCE_ENTITY_POLY_SEQ category.
       */
      comp_id_2?: string;
      /**
       * The entity component identifier entity containing the linkage.
       */
      component_id: number;
      /**
       * For a polymer entity, the sequence number in the first of
       *  the two components making the linkage.
       *
       *  This data item is a pointer to _pdbx_reference_entity_poly_seq.num
       *  in the PDBX_REFERENCE_ENTITY_POLY_SEQ category.
       */
      entity_seq_num_1?: number;
      /**
       * For a polymer entity, the sequence number in the second of
       *  the two components making the linkage.
       *
       *  This data item is a pointer to _pdbx_reference_entity_poly_seq.num
       *  in the PDBX_REFERENCE_ENTITY_POLY_SEQ category.
       */
      entity_seq_num_2?: number;
      /**
       * The value of _pdbx_reference_entity_poly_link.link_id uniquely identifies
       *  a linkage within a polymer entity.
       */
      link_id: number;
      /**
       * The value of _pdbx_reference_entity_poly_link.prd_id is a reference
       *  _pdbx_reference_entity_list.prd_id in the PDBX_REFERENCE_ENTITY_POLY category.
       */
      prd_id: string;
      /**
       * The reference entity id of the polymer entity containing the linkage.
       *
       *  This data item is a pointer to _pdbx_reference_entity_poly.ref_entity_id
       *  in the PDBX_REFERENCE_ENTITY_POLY category.
       */
      ref_entity_id: string;
      /**
       * The bond order target for the non-standard linkage.
       */
      value_order?: "arom" | "delo" | "doub" | "pi" | "poly" | "quad" | "sing" | "trip";
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_reference_entity_poly_seq?: [
    {
      /**
       * A flag to indicate that sequence heterogeneity at this monomer position.
       */
      hetero: "N" | "Y";
      /**
       * This data item is the chemical component identifier of monomer.
       */
      mon_id: string;
      /**
       * The value of _pdbx_reference_entity_poly_seq.num must uniquely and sequentially
       *  identify a record in the PDBX_REFERENCE_ENTITY_POLY_SEQ list.
       *
       *  This value is conforms to author numbering conventions and does not map directly
       *  to the numbering conventions used for _entity_poly_seq.num.
       */
      num: number;
      /**
       * A flag to indicate that this monomer is observed in the instance example.
       */
      observed?: "N" | "Y";
      /**
       * This data item is the chemical component identifier for the parent component corresponding to this monomer.
       */
      parent_mon_id?: string;
      /**
       * The value of _pdbx_reference_entity_poly_seq.prd_id is a reference
       * 	       _pdbx_reference_entity_poly.prd_id in the  PDBX_REFERENCE_ENTITY_POLY category.
       */
      prd_id: string;
      /**
       * The value of _pdbx_reference_entity_poly_seq.ref_entity_id is a reference
       *  to _pdbx_reference_entity_poly.ref_entity_id in PDBX_REFERENCE_ENTITY_POLY category.
       */
      ref_entity_id: string;
    },
    ...{
      /**
       * A flag to indicate that sequence heterogeneity at this monomer position.
       */
      hetero: "N" | "Y";
      /**
       * This data item is the chemical component identifier of monomer.
       */
      mon_id: string;
      /**
       * The value of _pdbx_reference_entity_poly_seq.num must uniquely and sequentially
       *  identify a record in the PDBX_REFERENCE_ENTITY_POLY_SEQ list.
       *
       *  This value is conforms to author numbering conventions and does not map directly
       *  to the numbering conventions used for _entity_poly_seq.num.
       */
      num: number;
      /**
       * A flag to indicate that this monomer is observed in the instance example.
       */
      observed?: "N" | "Y";
      /**
       * This data item is the chemical component identifier for the parent component corresponding to this monomer.
       */
      parent_mon_id?: string;
      /**
       * The value of _pdbx_reference_entity_poly_seq.prd_id is a reference
       * 	       _pdbx_reference_entity_poly.prd_id in the  PDBX_REFERENCE_ENTITY_POLY category.
       */
      prd_id: string;
      /**
       * The value of _pdbx_reference_entity_poly_seq.ref_entity_id is a reference
       *  to _pdbx_reference_entity_poly.ref_entity_id in PDBX_REFERENCE_ENTITY_POLY category.
       */
      ref_entity_id: string;
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_reference_entity_sequence?: [
    {
      /**
       * A flag to indicate a non-ribosomal entity.
       */
      NRP_flag?: "N" | "Y";
      /**
       * The one-letter-code sequence for this entity.  Non-standard monomers are represented as 'X'.
       */
      one_letter_codes?: string;
      /**
       * The value of _pdbx_reference_entity_sequence.prd_id is a reference
       * 	       _pdbx_reference_entity_list.prd_id in the  PDBX_REFERENCE_ENTITY_LIST category.
       */
      prd_id: string;
      /**
       * The value of _pdbx_reference_entity_sequence.ref_entity_id is a reference
       *  to _pdbx_reference_entity_list.ref_entity_id in PDBX_REFERENCE_ENTITY_LIST category.
       */
      ref_entity_id: string;
      /**
       * The monomer type for the sequence.
       */
      type?: "peptide-like" | "saccharide";
    },
    ...{
      /**
       * A flag to indicate a non-ribosomal entity.
       */
      NRP_flag?: "N" | "Y";
      /**
       * The one-letter-code sequence for this entity.  Non-standard monomers are represented as 'X'.
       */
      one_letter_codes?: string;
      /**
       * The value of _pdbx_reference_entity_sequence.prd_id is a reference
       * 	       _pdbx_reference_entity_list.prd_id in the  PDBX_REFERENCE_ENTITY_LIST category.
       */
      prd_id: string;
      /**
       * The value of _pdbx_reference_entity_sequence.ref_entity_id is a reference
       *  to _pdbx_reference_entity_list.ref_entity_id in PDBX_REFERENCE_ENTITY_LIST category.
       */
      ref_entity_id: string;
      /**
       * The monomer type for the sequence.
       */
      type?: "peptide-like" | "saccharide";
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_reference_entity_src_nat?: [
    {
      /**
       * The Americal Tissue Culture Collection code for organism from which the entity was isolated.
       */
      atcc?: string;
      /**
       * The database code for this source information
       */
      db_code?: string;
      /**
       * The database name for this source information
       */
      db_name?: string;
      /**
       * The value of _pdbx_reference_entity_src_nat.ordinal distinguishes
       * 	       source details for this entity.
       */
      ordinal: number;
      /**
       * The scientific name of the organism from which the entity was isolated.
       */
      organism_scientific?: string;
      /**
       * The value of _pdbx_reference_entity_src_nat.prd_id is a reference
       * 	       _pdbx_reference_entity_list.prd_id in the  PDBX_REFERENCE_ENTITY_LIST category.
       */
      prd_id: string;
      /**
       * The value of _pdbx_reference_entity_src_nat.ref_entity_id is a reference
       *  to _pdbx_reference_entity_list.ref_entity_id in PDBX_REFERENCE_ENTITY_LIST category.
       */
      ref_entity_id: string;
      /**
       * The data source for this information.
       */
      source?: string;
      /**
       * A identifier within the data source for this information.
       */
      source_id?: string;
      /**
       * The NCBI TaxId of the organism from which the entity was isolated.
       */
      taxid?: string;
    },
    ...{
      /**
       * The Americal Tissue Culture Collection code for organism from which the entity was isolated.
       */
      atcc?: string;
      /**
       * The database code for this source information
       */
      db_code?: string;
      /**
       * The database name for this source information
       */
      db_name?: string;
      /**
       * The value of _pdbx_reference_entity_src_nat.ordinal distinguishes
       * 	       source details for this entity.
       */
      ordinal: number;
      /**
       * The scientific name of the organism from which the entity was isolated.
       */
      organism_scientific?: string;
      /**
       * The value of _pdbx_reference_entity_src_nat.prd_id is a reference
       * 	       _pdbx_reference_entity_list.prd_id in the  PDBX_REFERENCE_ENTITY_LIST category.
       */
      prd_id: string;
      /**
       * The value of _pdbx_reference_entity_src_nat.ref_entity_id is a reference
       *  to _pdbx_reference_entity_list.ref_entity_id in PDBX_REFERENCE_ENTITY_LIST category.
       */
      ref_entity_id: string;
      /**
       * The data source for this information.
       */
      source?: string;
      /**
       * A identifier within the data source for this information.
       */
      source_id?: string;
      /**
       * The NCBI TaxId of the organism from which the entity was isolated.
       */
      taxid?: string;
    }[]
  ];
  pdbx_reference_molecule?: {
    /**
     * For entities represented as single molecules, the identifier
     *  corresponding to the chemical definition for the molecule.
     */
    chem_comp_id?: string;
    /**
     * Broadly defines the function of the entity.
     */
    class?:
      | "Antagonist"
      | "Anthelmintic"
      | "Antibiotic"
      | "Antibiotic, Anthelmintic"
      | "Antibiotic, Antimicrobial"
      | "Antibiotic, Antineoplastic"
      | "Anticancer"
      | "Anticoagulant"
      | "Anticoagulant, Antithrombotic"
      | "Antifungal"
      | "Antigen"
      | "Antiinflammatory"
      | "Antimicrobial"
      | "Antimicrobial, Antiparasitic, Antibiotic"
      | "Antimicrobial, Antiretroviral"
      | "Antimicrobial, Antitumor"
      | "Antineoplastic"
      | "Antiparasitic"
      | "Antiretroviral"
      | "Antithrombotic"
      | "Antitumor"
      | "Antiviral"
      | "CASPASE inhibitor"
      | "Chaperone binding"
      | "Drug delivery"
      | "Enzyme inhibitor"
      | "Glycan component"
      | "Growth factor"
      | "Immunosuppressant"
      | "Inducer"
      | "Inhibitor"
      | "Lantibiotic"
      | "Metabolism"
      | "Metal transport"
      | "Nutrient"
      | "Oxidation-reduction"
      | "Protein binding"
      | "Receptor"
      | "Substrate analog"
      | "Synthetic opioid"
      | "Thrombin inhibitor"
      | "Thrombin inhibitor, Trypsin inhibitor"
      | "Toxin"
      | "Transition state mimetic"
      | "Transport activator"
      | "Trypsin inhibitor"
      | "Unknown"
      | "Water retention";
    /**
     * Evidence for the assignment of _pdbx_reference_molecule.class
     */
    class_evidence_code?: string;
    /**
     * Special details about this molecule.
     */
    compound_details?: string;
    /**
     * Description of this molecule.
     */
    description?: string;
    /**
     * The formula for the reference entity. Formulae are written
     *  according to the rules:
     *
     *  1. Only recognised element symbols may be used.
     *
     *  2. Each element symbol is followed by a 'count' number. A count
     *     of '1' may be omitted.
     *
     *  3. A space or parenthesis must separate each element symbol and
     *     its count, but in general parentheses are not used.
     *
     *  4. The order of elements depends on whether or not carbon is
     *     present. If carbon is present, the order should be: C, then
     *     H, then the other elements in alphabetical order of their
     *     symbol. If carbon is not present, the elements are listed
     *     purely in alphabetic order of their symbol. This is the
     *     'Hill' system used by Chemical Abstracts.
     */
    formula?: string;
    /**
     * Formula mass in daltons of the entity.
     */
    formula_weight?: number;
    /**
     * A name of the entity.
     */
    name?: string;
    /**
     * The value of _pdbx_reference_molecule.prd_id is the unique identifier
     *  for the reference molecule in this family.
     *
     *  By convention this ID uniquely identifies the reference molecule in
     *  in the PDB reference dictionary.
     *
     *  The ID has the template form PRD_dddddd (e.g. PRD_000001)
     */
    prd_id: string;
    /**
     * Defines the current PDB release status for this molecule definition.
     */
    release_status?: "HOLD" | "OBS" | "REL" | "WAIT";
    /**
     * Assigns the identifier of the reference molecule that has replaced this molecule.
     */
    replaced_by?: string;
    /**
     * Assigns the identifier for the reference molecule which have been replaced
     *  by this reference molecule.
     *  Multiple molecule identifier codes should be separated by commas.
     */
    replaces?: string;
    /**
     * Defines how this entity is represented in PDB data files.
     */
    represent_as?: "branched" | "polymer" | "single molecule";
    /**
     * The PDB accession code for the entry containing a representative example of this molecule.
     */
    representative_PDB_id_code?: string;
    /**
     * Defines the structural classification of the entity.
     */
    type?:
      | "Amino acid"
      | "Aminoglycoside"
      | "Ansamycin"
      | "Anthracycline"
      | "Anthraquinone"
      | "Chalkophore"
      | "Chalkophore, Polypeptide"
      | "Chromophore"
      | "Cyclic depsipeptide"
      | "Cyclic lipopeptide"
      | "Cyclic peptide"
      | "Glycopeptide"
      | "Heterocyclic"
      | "Imino sugar"
      | "Keto acid"
      | "Lipoglycopeptide"
      | "Lipopeptide"
      | "Macrolide"
      | "Non-polymer"
      | "Nucleoside"
      | "Oligopeptide"
      | "Oligosaccharide"
      | "Peptaibol"
      | "Peptide-like"
      | "Polycyclic"
      | "Polypeptide"
      | "Polysaccharide"
      | "Quinolone"
      | "Siderophore"
      | "Thiolactone"
      | "Thiopeptide"
      | "Unknown";
    /**
     * Evidence for the assignment of _pdbx_reference_molecule.type
     */
    type_evidence_code?: string;
  };
  /**
   * @minItems 1
   */
  pdbx_reference_molecule_annotation?: [
    {
      /**
       * The value of _pdbx_reference_molecule_annotation.family_prd_id is a reference to
       *  _pdbx_reference_molecule_list.family_prd_id in category PDBX_REFERENCE_MOLECULE_FAMILY_LIST.
       */
      family_prd_id: string;
      /**
       * This data item distinguishes anotations for this entity.
       */
      ordinal: number;
      /**
       * This data item is a pointer to _pdbx_reference_molecule.prd_id in the
       *  PDB_REFERENCE_MOLECULE category.
       */
      prd_id?: string;
      /**
       * The source of the annoation for this entity.
       */
      source?: string;
      /**
       * Text describing the annotation for this entity.
       */
      text?: string;
      /**
       * Type of annotation for this entity.
       */
      type?: string;
    },
    ...{
      /**
       * The value of _pdbx_reference_molecule_annotation.family_prd_id is a reference to
       *  _pdbx_reference_molecule_list.family_prd_id in category PDBX_REFERENCE_MOLECULE_FAMILY_LIST.
       */
      family_prd_id: string;
      /**
       * This data item distinguishes anotations for this entity.
       */
      ordinal: number;
      /**
       * This data item is a pointer to _pdbx_reference_molecule.prd_id in the
       *  PDB_REFERENCE_MOLECULE category.
       */
      prd_id?: string;
      /**
       * The source of the annoation for this entity.
       */
      source?: string;
      /**
       * Text describing the annotation for this entity.
       */
      text?: string;
      /**
       * Type of annotation for this entity.
       */
      type?: string;
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_reference_molecule_details?: [
    {
      /**
       * The value of _pdbx_reference_molecule_details.family_prd_id is a reference to
       *  _pdbx_reference_molecule_list.family_prd_id' in category PDBX_REFERENCE_MOLECULE_FAMILY.
       */
      family_prd_id: string;
      /**
       * The value of _pdbx_reference_molecule_details.ordinal is an ordinal that
       *  distinguishes each descriptive text for this entity.
       */
      ordinal: number;
      /**
       * A data source of this information (e.g. PubMed, Merck Index)
       */
      source?: string;
      /**
       * A identifier within the data source for this information.
       */
      source_id?: string;
      /**
       * The text of the description of special aspects of the entity.
       */
      text?: string;
    },
    ...{
      /**
       * The value of _pdbx_reference_molecule_details.family_prd_id is a reference to
       *  _pdbx_reference_molecule_list.family_prd_id' in category PDBX_REFERENCE_MOLECULE_FAMILY.
       */
      family_prd_id: string;
      /**
       * The value of _pdbx_reference_molecule_details.ordinal is an ordinal that
       *  distinguishes each descriptive text for this entity.
       */
      ordinal: number;
      /**
       * A data source of this information (e.g. PubMed, Merck Index)
       */
      source?: string;
      /**
       * A identifier within the data source for this information.
       */
      source_id?: string;
      /**
       * The text of the description of special aspects of the entity.
       */
      text?: string;
    }[]
  ];
  pdbx_reference_molecule_family?: {
    /**
     * The value of _pdbx_reference_entity.family_prd_id must uniquely identify a record in the
     *  PDBX_REFERENCE_MOLECULE_FAMILY list.
     *
     *  By convention this ID uniquely identifies the reference family in
     *  in the PDB reference dictionary.
     *
     *  The ID has the template form FAM_dddddd (e.g. FAM_000001)
     */
    family_prd_id: string;
    /**
     * The entity family name.
     */
    name?: string;
    /**
     * Assigns the current PDB release status for this family.
     */
    release_status?: "HOLD" | "OBS" | "REL" | "WAIT";
    /**
     * Assigns the identifier of the family that has replaced this component.
     */
    replaced_by?: string;
    /**
     * Assigns the identifier for the family which have been replaced by this family.
     *  Multiple family identifier codes should be separated by commas.
     */
    replaces?: string;
  };
  /**
   * @minItems 1
   */
  pdbx_reference_molecule_features?: [
    {
      /**
       * The value of _pdbx_reference_molecule_features.family_prd_id is a reference to
       *  _pdbx_reference_molecule_list.family_prd_id in category PDBX_REFERENCE_MOLECULE_FAMILY_LIST.
       */
      family_prd_id: string;
      /**
       * The value of _pdbx_reference_molecule_features.ordinal distinguishes
       * 	       each feature for this entity.
       */
      ordinal: number;
      /**
       * The value of _pdbx_reference_molecule_features.prd_id is a reference
       * 	       _pdbx_reference_molecule.prd_id in the  PDBX_REFERENCE_MOLECULE category.
       */
      prd_id: string;
      /**
       * The information source for the component feature.
       */
      source?: string;
      /**
       * The value of _pdbx_reference_molecule_features.source_ordinal provides
       * 	       the priority order of features from a particular source or database.
       */
      source_ordinal?: number;
      /**
       * The entity feature type.
       */
      type?: string;
      /**
       * The entity feature value.
       */
      value?: string;
    },
    ...{
      /**
       * The value of _pdbx_reference_molecule_features.family_prd_id is a reference to
       *  _pdbx_reference_molecule_list.family_prd_id in category PDBX_REFERENCE_MOLECULE_FAMILY_LIST.
       */
      family_prd_id: string;
      /**
       * The value of _pdbx_reference_molecule_features.ordinal distinguishes
       * 	       each feature for this entity.
       */
      ordinal: number;
      /**
       * The value of _pdbx_reference_molecule_features.prd_id is a reference
       * 	       _pdbx_reference_molecule.prd_id in the  PDBX_REFERENCE_MOLECULE category.
       */
      prd_id: string;
      /**
       * The information source for the component feature.
       */
      source?: string;
      /**
       * The value of _pdbx_reference_molecule_features.source_ordinal provides
       * 	       the priority order of features from a particular source or database.
       */
      source_ordinal?: number;
      /**
       * The entity feature type.
       */
      type?: string;
      /**
       * The entity feature value.
       */
      value?: string;
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_reference_molecule_list?: [
    {
      /**
       * The value of _pdbx_reference_molecule_list.family_prd_id is a reference to
       *  _pdbx_reference_molecule_family.family_prd_id' in category PDBX_REFERENCE_MOLECULE_FAMILY.
       */
      family_prd_id: string;
      /**
       * The value of _pdbx_reference_molecule_list.prd_id is the unique identifier
       *  for the reference molecule in this family.
       *
       *  By convention this ID uniquely identifies the reference molecule in
       *  in the PDB reference dictionary.
       *
       *  The ID has the template form PRD_dddddd (e.g. PRD_000001)
       */
      prd_id: string;
    },
    ...{
      /**
       * The value of _pdbx_reference_molecule_list.family_prd_id is a reference to
       *  _pdbx_reference_molecule_family.family_prd_id' in category PDBX_REFERENCE_MOLECULE_FAMILY.
       */
      family_prd_id: string;
      /**
       * The value of _pdbx_reference_molecule_list.prd_id is the unique identifier
       *  for the reference molecule in this family.
       *
       *  By convention this ID uniquely identifies the reference molecule in
       *  in the PDB reference dictionary.
       *
       *  The ID has the template form PRD_dddddd (e.g. PRD_000001)
       */
      prd_id: string;
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_reference_molecule_related_structures?: [
    {
      /**
       * A link to related reference information in the citation category.
       */
      citation_id?: string;
      /**
       * The database accession code for the related structure reference.
       */
      db_accession?: string;
      /**
       * The database identifier code for the related structure reference.
       */
      db_code?: string;
      /**
       * The database name for the related structure reference.
       */
      db_name?: string;
      /**
       * The value of _pdbx_reference_molecule_related_structures.family_prd_id is a reference to
       *  _pdbx_reference_molecule_list.family_prd_id in category PDBX_REFERENCE_MOLECULE_FAMILY_LIST.
       */
      family_prd_id: string;
      /**
       * The formula for the reference entity. Formulae are written
       *  according to the rules:
       *
       *  1. Only recognised element symbols may be used.
       *
       *  2. Each element symbol is followed by a 'count' number. A count
       *     of '1' may be omitted.
       *
       *  3. A space or parenthesis must separate each element symbol and
       *     its count, but in general parentheses are not used.
       *
       *  4. The order of elements depends on whether or not carbon is
       *     present. If carbon is present, the order should be: C, then
       *     H, then the other elements in alphabetical order of their
       *     symbol. If carbon is not present, the elements are listed
       *     purely in alphabetic order of their symbol. This is the
       *     'Hill' system used by Chemical Abstracts.
       */
      formula?: string;
      /**
       * The chemical name for the structure entry in the related database
       */
      name?: string;
      /**
       * The value of _pdbx_reference_molecule_related_structures.ordinal distinguishes
       *  related structural data for each entity.
       */
      ordinal: number;
    },
    ...{
      /**
       * A link to related reference information in the citation category.
       */
      citation_id?: string;
      /**
       * The database accession code for the related structure reference.
       */
      db_accession?: string;
      /**
       * The database identifier code for the related structure reference.
       */
      db_code?: string;
      /**
       * The database name for the related structure reference.
       */
      db_name?: string;
      /**
       * The value of _pdbx_reference_molecule_related_structures.family_prd_id is a reference to
       *  _pdbx_reference_molecule_list.family_prd_id in category PDBX_REFERENCE_MOLECULE_FAMILY_LIST.
       */
      family_prd_id: string;
      /**
       * The formula for the reference entity. Formulae are written
       *  according to the rules:
       *
       *  1. Only recognised element symbols may be used.
       *
       *  2. Each element symbol is followed by a 'count' number. A count
       *     of '1' may be omitted.
       *
       *  3. A space or parenthesis must separate each element symbol and
       *     its count, but in general parentheses are not used.
       *
       *  4. The order of elements depends on whether or not carbon is
       *     present. If carbon is present, the order should be: C, then
       *     H, then the other elements in alphabetical order of their
       *     symbol. If carbon is not present, the elements are listed
       *     purely in alphabetic order of their symbol. This is the
       *     'Hill' system used by Chemical Abstracts.
       */
      formula?: string;
      /**
       * The chemical name for the structure entry in the related database
       */
      name?: string;
      /**
       * The value of _pdbx_reference_molecule_related_structures.ordinal distinguishes
       *  related structural data for each entity.
       */
      ordinal: number;
    }[]
  ];
  /**
   * @minItems 1
   */
  pdbx_reference_molecule_synonyms?: [
    {
      /**
       * The value of _pdbx_reference_molecule_synonyms.family_prd_id is a reference to
       *  _pdbx_reference_molecule_list.family_prd_id in category PDBX_REFERENCE_MOLECULE_FAMILY_LIST.
       */
      family_prd_id: string;
      /**
       * A synonym name for the entity.
       */
      name?: string;
      /**
       * The value of _pdbx_reference_molecule_synonyms.ordinal is an ordinal
       * 	       to distinguish synonyms for this entity.
       */
      ordinal: number;
      /**
       * The value of _pdbx_reference_molecule_synonyms.prd_id is a reference
       * 	       _pdbx_reference_molecule.prd_id in the  PDBX_REFERENCE_MOLECULE category.
       */
      prd_id: string;
      /**
       * The source of this synonym name for the entity.
       */
      source?: string;
    },
    ...{
      /**
       * The value of _pdbx_reference_molecule_synonyms.family_prd_id is a reference to
       *  _pdbx_reference_molecule_list.family_prd_id in category PDBX_REFERENCE_MOLECULE_FAMILY_LIST.
       */
      family_prd_id: string;
      /**
       * A synonym name for the entity.
       */
      name?: string;
      /**
       * The value of _pdbx_reference_molecule_synonyms.ordinal is an ordinal
       * 	       to distinguish synonyms for this entity.
       */
      ordinal: number;
      /**
       * The value of _pdbx_reference_molecule_synonyms.prd_id is a reference
       * 	       _pdbx_reference_molecule.prd_id in the  PDBX_REFERENCE_MOLECULE category.
       */
      prd_id: string;
      /**
       * The source of this synonym name for the entity.
       */
      source?: string;
    }[]
  ];
  /**
   * @minItems 1
   */
  rcsb_bird_citation?: [
    {
      /**
       * The value of _rcsb_bird_citation.id must uniquely identify a record in the
       *  rcsb_bird_citation list.
       */
      id: string;
      /**
       * Abbreviated name of the cited journal as given in the
       *  Chemical Abstracts Service Source Index.
       */
      journal_abbrev?: string;
      /**
       * Volume number of the journal cited; relevant for journal
       *  articles.
       */
      journal_volume?: string;
      /**
       * The first page of the rcsb_bird_citation; relevant for journal
       *  articles, books and book chapters.
       */
      page_first?: string;
      /**
       * The last page of the rcsb_bird_citation; relevant for journal
       *  articles, books and book chapters.
       */
      page_last?: string;
      /**
       * Document Object Identifier used by doi.org to uniquely
       *  specify bibliographic entry.
       */
      pdbx_database_id_DOI?: string;
      /**
       * Ascession number used by PubMed to categorize a specific
       *  bibliographic entry.
       */
      pdbx_database_id_PubMed?: number;
      rcsb_authors?: string[];
      /**
       * The title of the rcsb_bird_citation; relevant for journal articles, books
       *  and book chapters.
       */
      title?: string;
      /**
       * The year of the rcsb_bird_citation; relevant for journal articles, books
       *  and book chapters.
       */
      year?: number;
    },
    ...{
      /**
       * The value of _rcsb_bird_citation.id must uniquely identify a record in the
       *  rcsb_bird_citation list.
       */
      id: string;
      /**
       * Abbreviated name of the cited journal as given in the
       *  Chemical Abstracts Service Source Index.
       */
      journal_abbrev?: string;
      /**
       * Volume number of the journal cited; relevant for journal
       *  articles.
       */
      journal_volume?: string;
      /**
       * The first page of the rcsb_bird_citation; relevant for journal
       *  articles, books and book chapters.
       */
      page_first?: string;
      /**
       * The last page of the rcsb_bird_citation; relevant for journal
       *  articles, books and book chapters.
       */
      page_last?: string;
      /**
       * Document Object Identifier used by doi.org to uniquely
       *  specify bibliographic entry.
       */
      pdbx_database_id_DOI?: string;
      /**
       * Ascession number used by PubMed to categorize a specific
       *  bibliographic entry.
       */
      pdbx_database_id_PubMed?: number;
      rcsb_authors?: string[];
      /**
       * The title of the rcsb_bird_citation; relevant for journal articles, books
       *  and book chapters.
       */
      title?: string;
      /**
       * The year of the rcsb_bird_citation; relevant for journal articles, books
       *  and book chapters.
       */
      year?: number;
    }[]
  ];
  /**
   * @minItems 1
   */
  rcsb_chem_comp_annotation?: [
    {
      /**
       * An identifier for the annotation.
       */
      annotation_id?: string;
      /**
       * Identifies the version of the annotation assignment.
       */
      assignment_version?: string;
      /**
       * A description for the annotation.
       */
      description?: string;
      /**
       * A name for the annotation.
       */
      name?: string;
      /**
       * Code identifying the individual, organization or program that
       *  assigned the annotation.
       */
      provenance_source?: string;
      /**
       * A type or category of the annotation.
       */
      type?:
        | "ATC"
        | "Carbohydrate Anomer"
        | "Carbohydrate Isomer"
        | "Carbohydrate Primary Carbonyl Group"
        | "Carbohydrate Ring"
        | "Generating Enzyme"
        | "Modification Type"
        | "PSI-MOD";
      annotation_lineage?: {
        /**
         * Members of the annotation lineage as parent lineage depth (1-N)
         */
        depth?: number;
        /**
         * Members of the annotation lineage as parent class identifiers.
         */
        id?: string;
        /**
         * Members of the annotation lineage as parent class names.
         */
        name?: string;
      }[];
    },
    ...{
      /**
       * An identifier for the annotation.
       */
      annotation_id?: string;
      /**
       * Identifies the version of the annotation assignment.
       */
      assignment_version?: string;
      /**
       * A description for the annotation.
       */
      description?: string;
      /**
       * A name for the annotation.
       */
      name?: string;
      /**
       * Code identifying the individual, organization or program that
       *  assigned the annotation.
       */
      provenance_source?: string;
      /**
       * A type or category of the annotation.
       */
      type?:
        | "ATC"
        | "Carbohydrate Anomer"
        | "Carbohydrate Isomer"
        | "Carbohydrate Primary Carbonyl Group"
        | "Carbohydrate Ring"
        | "Generating Enzyme"
        | "Modification Type"
        | "PSI-MOD";
      annotation_lineage?: {
        /**
         * Members of the annotation lineage as parent lineage depth (1-N)
         */
        depth?: number;
        /**
         * Members of the annotation lineage as parent class identifiers.
         */
        id?: string;
        /**
         * Members of the annotation lineage as parent class names.
         */
        name?: string;
      }[];
    }[]
  ];
  rcsb_chem_comp_container_identifiers?: {
    atc_codes?: string[];
    /**
     * The chemical component identifier.
     */
    comp_id: string;
    /**
     * The DrugBank identifier corresponding to the chemical component.
     */
    drugbank_id?: string;
    /**
     * The BIRD definition identifier.
     */
    prd_id?: string;
    /**
     * A unique identifier for the chemical definition in this container.
     */
    rcsb_id?: string;
    subcomponent_ids?: string[];
  };
  rcsb_chem_comp_descriptor?: {
    /**
     * Standard IUPAC International Chemical Identifier (InChI) descriptor for the chemical component.
     *
     *    InChI, the IUPAC International Chemical Identifier,
     *    by Stephen R Heller, Alan McNaught, Igor Pletnev, Stephen Stein and Dmitrii Tchekhovskoi,
     *    Journal of Cheminformatics, 2015, 7:23;
     */
    InChI?: string;
    /**
     * Standard IUPAC International Chemical Identifier (InChI) descriptor key
     *  for the chemical component
     *
     *  InChI, the IUPAC International Chemical Identifier,
     *  by Stephen R Heller, Alan McNaught, Igor Pletnev, Stephen Stein and Dmitrii Tchekhovskoi,
     *  Journal of Cheminformatics, 2015, 7:23
     */
    InChIKey?: string;
    /**
     * Simplified molecular-input line-entry system (SMILES) descriptor for the chemical component.
     *
     *    Weininger D (February 1988). "SMILES, a chemical language and information system. 1.
     *    Introduction to methodology and encoding rules". Journal of Chemical Information and Modeling. 28 (1): 31-6.
     *
     *    Weininger D, Weininger A, Weininger JL (May 1989).
     *    "SMILES. 2. Algorithm for generation of unique SMILES notation",
     *    Journal of Chemical Information and Modeling. 29 (2): 97-101.
     */
    SMILES?: string;
    /**
     * Simplified molecular-input line-entry system (SMILES) descriptor for the chemical
     *  component including stereochemical features.
     *
     *  Weininger D (February 1988). "SMILES, a chemical language and information system. 1.
     *  Introduction to methodology and encoding rules".
     *  Journal of Chemical Information and Modeling. 28 (1): 31-6.
     *
     *  Weininger D, Weininger A, Weininger JL (May 1989).
     *  "SMILES. 2. Algorithm for generation of unique SMILES notation".
     *  Journal of Chemical Information and Modeling. 29 (2): 97-101.
     */
    SMILES_stereo?: string;
    /**
     * The chemical component identifier.
     */
    comp_id: string;
  };
  rcsb_chem_comp_info?: {
    /**
     * Chemical component total atom count
     */
    atom_count?: number;
    /**
     * Chemical component chiral atom count
     */
    atom_count_chiral?: number;
    /**
     * Chemical component heavy atom count
     */
    atom_count_heavy?: number;
    /**
     * Chemical component total bond count
     */
    bond_count?: number;
    /**
     * Chemical component aromatic bond count
     */
    bond_count_aromatic?: number;
    /**
     * The chemical component identifier.
     */
    comp_id: string;
    /**
     * The date the chemical definition was first deposited in the PDB repository.
     */
    initial_deposition_date?: string;
    /**
     * The initial date the chemical definition was released in the PDB repository.
     */
    initial_release_date?: string;
    /**
     * The release status of the chemical definition.
     */
    release_status?: "DEL" | "HOLD" | "HPUB" | "OBS" | "REF_ONLY" | "REL";
    /**
     * The date of last revision of the chemical definition.
     */
    revision_date?: string;
  };
  /**
   * @minItems 1
   */
  rcsb_chem_comp_related?: [
    {
      /**
       * The value of _rcsb_chem_comp_related.comp_id is a reference to
       *  a chemical component definition.
       */
      comp_id: string;
      /**
       * The value of _rcsb_chem_comp_related.ordinal distinguishes
       *  related examples for each chemical component.
       */
      ordinal: number;
      /**
       * The method used to establish the resource correspondence.
       */
      related_mapping_method?:
        | "assigned by DrugBank resource"
        | "assigned by PDB"
        | "assigned by PubChem resource"
        | "matching ChEMBL ID in Pharos"
        | "matching InChIKey in DrugBank"
        | "matching InChIKey in PubChem"
        | "matching InChIKey-prefix in DrugBank"
        | "matching by RESID resource";
      /**
       * The resource identifier code for the related chemical reference.
       */
      resource_accession_code?: string;
      /**
       * The resource name for the related chemical reference.
       */
      resource_name?: "CAS" | "CCDC/CSD" | "ChEBI" | "ChEMBL" | "DrugBank" | "Pharos" | "PubChem" | "RESID";
    },
    ...{
      /**
       * The value of _rcsb_chem_comp_related.comp_id is a reference to
       *  a chemical component definition.
       */
      comp_id: string;
      /**
       * The value of _rcsb_chem_comp_related.ordinal distinguishes
       *  related examples for each chemical component.
       */
      ordinal: number;
      /**
       * The method used to establish the resource correspondence.
       */
      related_mapping_method?:
        | "assigned by DrugBank resource"
        | "assigned by PDB"
        | "assigned by PubChem resource"
        | "matching ChEMBL ID in Pharos"
        | "matching InChIKey in DrugBank"
        | "matching InChIKey in PubChem"
        | "matching InChIKey-prefix in DrugBank"
        | "matching by RESID resource";
      /**
       * The resource identifier code for the related chemical reference.
       */
      resource_accession_code?: string;
      /**
       * The resource name for the related chemical reference.
       */
      resource_name?: "CAS" | "CCDC/CSD" | "ChEBI" | "ChEMBL" | "DrugBank" | "Pharos" | "PubChem" | "RESID";
    }[]
  ];
  /**
   * @minItems 1
   */
  rcsb_chem_comp_synonyms?: [
    {
      /**
       * The chemical component to which this synonym applies.
       */
      comp_id: string;
      /**
       * The synonym of this particular chemical component.
       */
      name?: string;
      /**
       * This data item is an ordinal index for the
       *  RCSB_CHEM_COMP_SYNONYMS category.
       */
      ordinal: number;
      /**
       * The provenance of this synonym.
       */
      provenance_source?:
        | "ACDLabs"
        | "Author"
        | "ChEBI"
        | "ChEMBL"
        | "DrugBank"
        | "GMML"
        | "Lexichem"
        | "OpenEye OEToolkits"
        | "OpenEye/Lexichem"
        | "PDB Reference Data"
        | "PDB Reference Data (Preferred)"
        | "PDB-CARE"
        | "PubChem"
        | "RESID";
      /**
       * This data item contains the synonym type.
       */
      type?:
        | "Brand Name"
        | "Common Name"
        | "Condensed IUPAC Carbohydrate Symbol"
        | "IUPAC Carbohydrate Symbol"
        | "Preferred Common Name"
        | "Preferred Name"
        | "Preferred Synonym"
        | "SNFG Carbohydrate Symbol"
        | "Synonym"
        | "Systematic Name";
    },
    ...{
      /**
       * The chemical component to which this synonym applies.
       */
      comp_id: string;
      /**
       * The synonym of this particular chemical component.
       */
      name?: string;
      /**
       * This data item is an ordinal index for the
       *  RCSB_CHEM_COMP_SYNONYMS category.
       */
      ordinal: number;
      /**
       * The provenance of this synonym.
       */
      provenance_source?:
        | "ACDLabs"
        | "Author"
        | "ChEBI"
        | "ChEMBL"
        | "DrugBank"
        | "GMML"
        | "Lexichem"
        | "OpenEye OEToolkits"
        | "OpenEye/Lexichem"
        | "PDB Reference Data"
        | "PDB Reference Data (Preferred)"
        | "PDB-CARE"
        | "PubChem"
        | "RESID";
      /**
       * This data item contains the synonym type.
       */
      type?:
        | "Brand Name"
        | "Common Name"
        | "Condensed IUPAC Carbohydrate Symbol"
        | "IUPAC Carbohydrate Symbol"
        | "Preferred Common Name"
        | "Preferred Name"
        | "Preferred Synonym"
        | "SNFG Carbohydrate Symbol"
        | "Synonym"
        | "Systematic Name";
    }[]
  ];
  /**
   * @minItems 1
   */
  rcsb_chem_comp_target?: [
    {
      /**
       * The value of _rcsb_chem_comp_target.comp_id is a reference to
       *  a chemical component definition.
       */
      comp_id: string;
      /**
       * The type of target interaction.
       */
      interaction_type?: string;
      /**
       * The chemical component target name.
       */
      name?: string;
      /**
       * The value of _rcsb_chem_comp_target.ordinal distinguishes
       *  related examples for each chemical component.
       */
      ordinal: number;
      /**
       * A code indicating the provenance of the target interaction assignment
       */
      provenance_source?: "DrugBank" | "PDB Primary Data";
      /**
       * The reference identifier code for the target interaction reference.
       */
      reference_database_accession_code?: string;
      /**
       * The reference database name for the target interaction.
       */
      reference_database_name?: "UniProt";
      target_actions?: string[];
    },
    ...{
      /**
       * The value of _rcsb_chem_comp_target.comp_id is a reference to
       *  a chemical component definition.
       */
      comp_id: string;
      /**
       * The type of target interaction.
       */
      interaction_type?: string;
      /**
       * The chemical component target name.
       */
      name?: string;
      /**
       * The value of _rcsb_chem_comp_target.ordinal distinguishes
       *  related examples for each chemical component.
       */
      ordinal: number;
      /**
       * A code indicating the provenance of the target interaction assignment
       */
      provenance_source?: "DrugBank" | "PDB Primary Data";
      /**
       * The reference identifier code for the target interaction reference.
       */
      reference_database_accession_code?: string;
      /**
       * The reference database name for the target interaction.
       */
      reference_database_name?: "UniProt";
      target_actions?: string[];
    }[]
  ];
  /**
   * @minItems 1
   */
  rcsb_schema_container_identifiers?: [
    {
      /**
       * Collection name associated with the data in the container.
       */
      collection_name: string;
      /**
       * Version string for the schema and collection.
       */
      collection_schema_version?: string;
      /**
       * Schema name associated with the data in the container.
       */
      schema_name: string;
    },
    ...{
      /**
       * Collection name associated with the data in the container.
       */
      collection_name: string;
      /**
       * Version string for the schema and collection.
       */
      collection_schema_version?: string;
      /**
       * Schema name associated with the data in the container.
       */
      schema_name: string;
    }[]
  ];
  /**
   * A unique identifier for the chemical definition in this container.
   */
  rcsb_id: string;
}
