/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * RCSB Exchange Database JSON schema derived from the repository_holdings content type schema. This schema supports collection repository_holdings_current_entry version 3.5.0. This schema is hosted in repository https://github.com/rcsb/py-rcsb.db/tree/master/rcsb.db/data/json-schema/json-schema-min-repository_holdings_current_entry.json and follows JSON schema specification version 4
 */
export interface SchemaRepositoryHoldingsCollectionRepositoryHoldingsCurrentEntryVersion350 {
  rcsb_repository_holdings_current?: {
    repository_content_types?: (
      | "2fo-fc Map"
      | "Combined NMR data (NEF)"
      | "Combined NMR data (NMR-STAR)"
      | "FASTA sequence"
      | "Map Coefficients"
      | "NMR chemical shifts"
      | "NMR restraints V1"
      | "NMR restraints V2"
      | "assembly PDB"
      | "assembly mmCIF"
      | "entry PDB"
      | "entry PDB bundle"
      | "entry PDBML"
      | "entry mmCIF"
      | "fo-fc Map"
      | "structure factors"
      | "validation 2fo-fc coefficients"
      | "validation data mmCIF"
      | "validation fo-fc coefficients"
      | "validation report"
      | "validation slider image"
    )[];
  };
  rcsb_repository_holdings_current_entry_container_identifiers?: {
    assembly_ids?: string[];
    /**
     * The PDB entry accession code.
     */
    entry_id: string;
    /**
     * The RCSB entry identifier.
     */
    rcsb_id?: string;
    /**
     * Identifier for the current data exchange status record.
     */
    update_id?: string;
  };
  /**
   * The RCSB entry identifier.
   */
  rcsb_id: string;
}
