/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GroupPolymerEntity {
  /**
   * A unique textual identifier for a group
   */
  rcsb_id: string;
  rcsb_group_container_identifiers: {
    /**
     * A unique textual identifier for a group
     */
    group_id: string;
    /**
     * A unique group provenance identifier
     */
    group_provenance_id:
      | "provenance_sequence_identity"
      | "provenance_matching_uniprot_accession"
      | "provenance_matching_deposit_group_id";
    /**
     * Member identifiers representing a higher level in the groping hierarchy that has parent-child relationship
     */
    parent_member_ids?: [string, ...string[]];
    /**
     * Member identifiers representing a group
     */
    group_member_ids: [string, ...string[]];
  };
  rcsb_group_info: {
    group_name?: string;
    group_description?: string;
    /**
     * Granularity of group members identifiers
     */
    group_members_granularity: "assembly" | "entry" | "polymer_entity" | "polymer_entity_instance";
    group_members_count: number;
    [k: string]: unknown;
  };
  rcsb_group_statistics?: {
    /**
     * The desired lower limit for the similarity between two members that belong to the same group
     */
    similarity_cutoff?: number;
    /**
     * Similarity score between two least similar group members
     */
    similarity_score_min?: number;
    /**
     * Similarity score between two most similar group members
     */
    similarity_score_max?: number;
  };
  rcsb_group_accession_info?: {
    /**
     * Identifies the version of the groups solution
     */
    version: number;
  };
  rcsb_group_related?: [
    {
      /**
       * A unique code assigned to a reference related the group
       */
      resource_accession_code?: string;
      /**
       * Defines the type of the resource describing related references
       */
      resource_name?: string;
      [k: string]: unknown;
    },
    ...{
      /**
       * A unique code assigned to a reference related the group
       */
      resource_accession_code?: string;
      /**
       * Defines the type of the resource describing related references
       */
      resource_name?: string;
      [k: string]: unknown;
    }[]
  ];
  rcsb_polymer_entity_group_members_rankings?: [
    {
      /**
       * Defines ranking option applicable to group members
       */
      ranking_criteria_type: "coverage";
      group_members: [
        {
          member_id: string;
          /**
           * Reflects a relationship between group members such that, for any two members the first is ranked higher (smaller rank value) than the second
           */
          rank: number;
          /**
           * Quantifies the criteria used for ranking
           */
          original_score?: number;
        },
        ...{
          member_id: string;
          /**
           * Reflects a relationship between group members such that, for any two members the first is ranked higher (smaller rank value) than the second
           */
          rank: number;
          /**
           * Quantifies the criteria used for ranking
           */
          original_score?: number;
        }[]
      ];
    },
    ...{
      /**
       * Defines ranking option applicable to group members
       */
      ranking_criteria_type: "coverage";
      group_members: [
        {
          member_id: string;
          /**
           * Reflects a relationship between group members such that, for any two members the first is ranked higher (smaller rank value) than the second
           */
          rank: number;
          /**
           * Quantifies the criteria used for ranking
           */
          original_score?: number;
        },
        ...{
          member_id: string;
          /**
           * Reflects a relationship between group members such that, for any two members the first is ranked higher (smaller rank value) than the second
           */
          rank: number;
          /**
           * Quantifies the criteria used for ranking
           */
          original_score?: number;
        }[]
      ];
    }[]
  ];
  rcsb_polymer_entity_group_sequence_alignment?: {
    /**
     * Abstract reference where group members can be aligned to generate a MSA
     */
    abstract_reference: {
      /**
       * Abstract reference length
       */
      length: number;
      /**
       * Sequence that represents the abstract reference
       */
      sequence?: string;
      [k: string]: unknown;
    };
    /**
     * List of alignments with core_entity canonical sequences
     */
    group_members_alignment: [
      {
        member_id: string;
        /**
         * Alignment scores
         */
        scores: {
          target_coverage: number;
          query_coverage: number;
          target_length: number;
          query_length: number;
          [k: string]: unknown;
        };
        /**
         * List of alignments with core_entity canonical sequences encoded as an array of triplets [query_begin, target_begin, length]
         */
        aligned_regions: [number, number, number][];
        [k: string]: unknown;
      },
      ...{
        member_id: string;
        /**
         * Alignment scores
         */
        scores: {
          target_coverage: number;
          query_coverage: number;
          target_length: number;
          query_length: number;
          [k: string]: unknown;
        };
        /**
         * List of alignments with core_entity canonical sequences encoded as an array of triplets [query_begin, target_begin, length]
         */
        aligned_regions: [number, number, number][];
        [k: string]: unknown;
      }[]
    ];
    [k: string]: unknown;
  };
}
