/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GroupProvenance {
  /**
   * A unique textual identifier for a group provenance
   */
  rcsb_id?: string;
  rcsb_group_provenance_container_identifiers?: {
    /**
     * A unique group provenance identifier
     */
    group_provenance_id:
      | "provenance_sequence_identity"
      | "provenance_matching_uniprot_accession"
      | "provenance_matching_deposit_group_id";
    [k: string]: unknown;
  };
  rcsb_group_aggregation_method?: {
    /**
     * Specifies the type of similarity criteria used to aggregate members into higher levels in the hierarchy
     */
    type: "sequence_identity" | "matching_uniprot_accession" | "matching_deposit_group_id";
    /**
     * The details on a method used to calculate cluster solutions
     */
    method: {
      /**
       * The name of the software or the method used to calculate cluster solutions
       */
      name: "mmseqs2" | "matching_reference_identity";
      /**
       * The version of the software.
       */
      version?: string;
      /**
       * Additional details describing the clustering process
       */
      details?: {
        /**
         * Defines the type of the description associated with the clustering process
         */
        type?: string;
        /**
         * Defines the name of the description associated with the clustering process
         */
        name?: string;
        /**
         * Defines the value associated with the clustering process
         */
        value?: number;
        /**
         * A description of special aspects of the clustering process
         */
        description?: string;
        [k: string]: unknown;
      }[];
    };
    similarity_criteria?: {
      /**
       * A function or similarity measure that quantifies the similarity between two members
       */
      similarity_function?: "rmsd" | "sequence_identity";
      [k: string]: unknown;
    };
  };
}
