/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON schema for identifier mapping in the 1D coordinate service
 */
export interface SequencePositionalAnnotations {
  /**
   * This item references an entry in core_entry
   */
  entry_id: string;
  /**
   * This item references an assembly in core_assembly
   */
  assembly_id?: string;
  /**
   * This item references an entity in core_polymer_entity
   */
  entity_id: string;
  /**
   * This item references an instance in core_polymer_entity_instance
   */
  asym_id?: string;
  /**
   * This item references an interface in core_interface
   */
  interface_id?: string;
  /**
   * This item references a partner of an interface in core_interface
   */
  interface_partner_index?: number;
}
