/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A tree node with a linkage to immediate parent(s) and all ancestors (node's lineage).
 */
export interface RCSBTreeNode {
  /**
   * Unique node identifier.
   */
  id: string;
  /**
   * Human-readable term associated with the node.
   */
  name?: string;
  /**
   * Node description.
   */
  description?: string;
  /**
   * Hierarchy depth.
   */
  depth?: number;
  /**
   * ID(s) of the node’s immediate parents.
   *
   * @minItems 1
   */
  parents?: [string, ...string[]];
  /**
   * Terms or IDs related to the node.
   *
   * @minItems 1
   */
  related?: [string, ...string[]];
}
