/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON schema for pairwise sequence alignments in the 1D coordinate service
 */
export interface SequencePairwiseAlignment {
  /**
   * Identifier of the query sequence
   */
  query_id: string;
  /**
   * Identifier of the target sequence
   */
  target_id: string;
  coverage: Coverage;
  /**
   * Aligned sequence regions between query and target sequences
   */
  aligned_regions: {
    /**
     * Target sequence start position
     */
    target_begin: number;
    /**
     * Query sequence start position
     */
    query_begin: number;
    /**
     * Target sequence start position
     */
    target_end: number;
    /**
     * Query sequence end position
     */
    query_end: number;
    /**
     * List of genomic indexes that are needed to complete the last nucleotide codon of a genome-protein sequence alignment
     */
    exon_shift?: number[];
  }[];
  /**
   * Target sequence start position in the alignment
   */
  target_begin: number;
  /**
   * Query sequence start position in the alignment
   */
  query_begin: number;
  /**
   * Target sequence end position in the alignment
   */
  target_end: number;
  /**
   * Query sequence end position in the alignment
   */
  query_end: number;
  /**
   * integer that identifies the DNA strand of genome alignments (1 positive strand / 2 negative strand)
   */
  orientation?: number;
}
/**
 * Alignment scores
 */
export interface Coverage {
  /**
   * Fraction of the target sequence covered by the alignment
   */
  target_coverage: number;
  /**
   * Fraction of the query sequence covered by the alignment
   */
  query_coverage: number;
  /**
   * Length of the full target sequence
   */
  target_length: number;
  /**
   * Length of the full query sequence
   */
  query_length: number;
}
